import test from 'node:test';
import assert from 'node:assert/strict';
import {leadSchema,selectorGuidance} from '../lib/lead';
import {POST} from '../app/api/leads/route';
const valid={name:'Alex Rao',business:'Example business',email:'alex@example.com',phone:'+91 9876543210',city:'Mumbai',industry:'hotels',area:'1200',requirements:'Reception with split AC and high ceilings.',consent:true,website:''};
function request(data:unknown,origin='http://localhost'){return new Request('http://localhost/api/leads',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(data)})}
test('validation requires correct contact, positive area and consent',()=>{assert.equal(leadSchema.safeParse(valid).success,true);for(const patch of [{email:'wrong'},{area:'-1'},{consent:false},{phone:'letters'},{requirements:'short'},{website:'spam'}])assert.equal(leadSchema.safeParse({...valid,...patch}).success,false);assert.equal(leadSchema.safeParse({...valid,area:''}).success,true)});
test('selector flags rooms and HVAC review without recommending a machine',()=>{const notes=selectorGuidance('separate','central').join(' ');assert.match(notes,/individual zones/);assert.match(notes,/not confirmed/);assert.doesNotMatch(notes,/guaranteed|buy this/i)});
test('unconnected and invalid requests never report acceptance',async()=>{delete process.env.LEAD_WEBHOOK_URL;const missing=await POST(request(valid));assert.equal(missing.status,503);assert.equal((await missing.json()).accepted,false);assert.equal((await POST(request({...valid,email:'wrong'}))).status,422);assert.equal((await POST(request(valid,'https://elsewhere.example'))).status,403)});
test('uses public Host when Next rewrites its internal request hostname',async()=>{const r=new Request('http://localhost:3100/api/leads',{method:'POST',headers:{'Content-Type':'application/json',Host:'127.0.0.1:3100',Origin:'http://127.0.0.1:3100'},body:JSON.stringify(valid)});assert.equal((await POST(r)).status,503)});
test('requires receiving acknowledgement, handles rejection and timeout',async()=>{const original=globalThis.fetch;process.env.LEAD_WEBHOOK_URL='https://receiver.example/leads';try{globalThis.fetch=async()=>new Response(JSON.stringify({accepted:true}),{status:202});assert.equal((await POST(request(valid))).status,202);globalThis.fetch=async()=>new Response(JSON.stringify({ok:true}),{status:200});assert.equal((await POST(request(valid))).status,502);globalThis.fetch=async()=>new Response(JSON.stringify({accepted:true}),{status:500});assert.equal((await POST(request(valid))).status,502);globalThis.fetch=async()=>{throw new Error('Timeout')};assert.equal((await POST(request(valid))).status,502)}finally{globalThis.fetch=original;delete process.env.LEAD_WEBHOOK_URL}});
