'use client';
import {useState} from 'react';
import Image from 'next/image';
import {scents} from '@/lib/content';
import {whatsappUrl} from '@/lib/whatsapp';
const images=['hotels-app.jpg','rooms-app.png','hume-spaces-hero.png','receptions-app.jpg','resorts-app.jpg','retail-stores-app.jpg'];
const idealFor=['Hotels, offices','Hotels, spas','Offices, retail','Hotels, showrooms','Gyms, retail','Offices, lounges'];
export default function FragranceCards({limit}:{limit?:number}){const [selected,setSelected]=useState<string[]>([]);function toggle(name:string){setSelected(items=>items.includes(name)?items.filter(i=>i!==name):[...items,name]);}return <><div className="fragrance-rows" aria-label="Fragrance profiles">{scents.slice(0,limit).map((s,n)=>{const added=selected.includes(s.name);return <article className="fragrance-row" key={s.name}><div className="fragrance-thumb"><Image src={`/images/spaces/${images[n%images.length]}`} alt={`${s.name} atmosphere inspiration`} fill sizes="80px"/></div><div className="fragrance-row-info"><h3>{s.name}</h3><p className="fragrance-notes">{s.notes}</p><p className="fragrance-ideal"><b>Ideal for:</b> {idealFor[n%idealFor.length]}</p></div><button type="button" className="fragrance-add" aria-label={`${added?'Remove':'Add'} ${s.name} ${added?'from':'to'} enquiry cart`} aria-pressed={added} onClick={()=>toggle(s.name)}><span aria-hidden="true">{added?'✓':'+'}</span></button></article>})}</div>{selected.length>0&&<aside className="fragrance-cart" aria-label="Fragrance enquiry cart"><div><p role="status"><b>{selected.length} {selected.length===1?'fragrance':'fragrances'} selected</b></p><p>{selected.join(', ')}</p></div><div className="fragrance-cart-actions"><a className="button" href={whatsappUrl(`these fragrance profiles: ${selected.join(', ')}`)} target="_blank" rel="noopener noreferrer">Enquire on WhatsApp <span aria-hidden="true">→</span></a><button type="button" className="text-link dark" onClick={()=>setSelected([])}>Clear</button></div><p className="cart-note">Enquiry only. Confirm availability and machine compatibility.</p></aside>}</>}

