'use client';
import {useState,useEffect} from 'react';
import Image from 'next/image';
import {scents} from '@/lib/content';
import {whatsappUrl} from '@/lib/whatsapp';
const images=['hotels-app.jpg','rooms-app.png','hume-spaces-hero.png','receptions-app.jpg','resorts-app.jpg','retail-stores-app.jpg'];
const idealFor=['Hotels, offices','Hotels, spas','Offices, retail','Hotels, showrooms','Gyms, retail','Offices, lounges'];
export default function FragranceCards({limit}:{limit?:number}){const [selected,setSelected]=useState<string[]>([]);useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem('hume-fragrance-cart')||'[]');if(Array.isArray(stored))setSelected([...new Set(stored.filter((s):s is string=>typeof s==='string'&&scents.some(item=>item.name===s)))]);}catch{}function sync(){try{const items=JSON.parse(localStorage.getItem('hume-fragrance-cart')||'[]');if(Array.isArray(items))setSelected(items.filter(s=>scents.some(item=>item.name===s)));}catch{}}window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);},[]);function save(items:string[]){try{localStorage.setItem('hume-fragrance-cart',JSON.stringify(items));}catch{}setSelected(items);window.dispatchEvent(new Event('hume-fragrance-change'));}function toggle(name:string){save(selected.includes(name)?selected.filter(i=>i!==name):[...selected,name]);}return <><div className="fragrance-rows" aria-label="Fragrance profiles">{scents.slice(0,limit).map((s,n)=>{const added=selected.includes(s.name);return <article className="fragrance-row" key={s.name}><div className="fragrance-thumb"><Image src={`/images/spaces/${images[n%images.length]}`} alt={`${s.name} atmosphere inspiration`} fill sizes="80px"/></div><div className="fragrance-row-info"><h3>{s.name}</h3><p className="fragrance-notes">{s.notes}</p><p className="fragrance-ideal"><b>Ideal for:</b> {idealFor[n%idealFor.length]}</p></div><button type="button" className="fragrance-add" aria-label={`${added?'Remove':'Add'} ${s.name} ${added?'from':'to'} enquiry cart`} aria-pressed={added} onClick={()=>toggle(s.name)}><span aria-hidden="true">{added?'✓':'+'}</span></button></article>})}</div>{selected.length>0&&<aside className="fragrance-cart" aria-label="Fragrance enquiry cart"><div><p role="status"><b>{selected.length} {selected.length===1?'fragrance':'fragrances'} selected</b></p><p>{selected.join(', ')}</p></div><div className="fragrance-cart-actions"><a className="button" href={whatsappUrl(`these fragrance profiles: ${selected.join(', ')}`)} target="_blank" rel="noopener noreferrer">Enquire on WhatsApp <span aria-hidden="true">→</span></a><button type="button" className="text-link dark" onClick={()=>save([])}>Clear</button></div><p className="cart-note">Enquiry only. Confirm availability and machine compatibility.</p></aside>}</>}


