'use client';
import WhatsAppButton from './WhatsAppButton';

import {useState,useEffect,useRef} from 'react';
import {useSearchParams} from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import {industries} from '@/lib/content';
import {selectorGuidance} from '@/lib/lead';

export default function Selector(){
 const params=useSearchParams();const initial=params.get('industry')||'hotels';
 const [industry,setIndustry]=useState(industries.some(i=>i.slug===initial)?initial:'other');
 const [step,setStep]=useState(0);const [area,setArea]=useState('');const [hours,setHours]=useState('10');const [height,setHeight]=useState('');const [layout,setLayout]=useState('open-plan');const [ventilation,setVentilation]=useState('split');const [zones,setZones]=useState((params.get('zones')||'').slice(0,300));
 const [result,setResult]=useState<{notes:string[];query:string}|null>(null);
 const resultTitle=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(result&&resultTitle.current){resultTitle.current.focus({preventScroll:true});resultTitle.current.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}},[result]);
 const current=industries.find(i=>i.slug===industry);
 const layouts=[['open-plan','Mostly open','One connected area'],['separate','Separate rooms','Rooms or multiple floors'],['mixed','Mixed / unsure','We can review the layout']];
 const airOptions=[['split','Split AC','Local room cooling'],['central','Central HVAC','Air distributed through ducts'],['open','Open / ventilated','Open doors or extraction'],['unsure','Not sure','Include this in the review']];
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(step<2){setStep(step+1);return;}const description=`Area: ${area} sq ft. Ceiling height: ${height||'not specified'}. Layout: ${layout}. Ventilation: ${ventilation}. Operating hours: ${hours} per day. Zones: ${zones||'not specified'}.`;const query=new URLSearchParams({industry,area,requirements:description}).toString();setResult({notes:selectorGuidance(layout,ventilation),query});}
 return <div className="wizard-layout"><form className="space-wizard" onSubmit={submit}><div className="wizard-progress" aria-label="Space brief steps">{['Your space','The details','Airflow'].map((label,n)=><button key={label} type="button" disabled={n>step} aria-current={n===step?'step':undefined} onClick={()=>{setStep(n);setResult(null);}}><span>0{n+1}</span>{label}</button>)}</div>
 {step===0&&<section className="wizard-step"><p className="eyebrow">FIRST, THE APPLICATION</p><h2>Choose your type of space</h2><p>Pick the closest match.</p><div className="wizard-applications" role="group" aria-label="Choose industry">{industries.map(i=><button key={i.slug} type="button" aria-pressed={industry===i.slug} onClick={()=>setIndustry(i.slug)}><div><Image src={`/images/spaces/${i.image}`} alt="" fill sizes="(max-width: 750px) 40vw, 180px"/></div><span>{i.short}<b>{industry===i.slug?'✓':'→'}</b></span></button>)}<button className="wizard-other" type="button" aria-pressed={industry==='other'} onClick={()=>setIndustry('other')}><div aria-hidden="true">＋</div><span>Other business<b>{industry==='other'?'✓':'→'}</b></span></button></div></section>}
 {step===1&&<section className="wizard-step"><p className="eyebrow">NEXT, THE BASICS</p><h2>Enter area and operating hours</h2><p>Approximate details are a useful start.</p><div className="field-grid"><label>Floor area · sq ft<input name="area" type="number" required min="1" max="10000000" value={area} onChange={e=>setArea(e.target.value)} placeholder="e.g. 1,200"/></label><label>Hours per day<input name="hours" type="number" required min="1" max="24" value={hours} onChange={e=>setHours(e.target.value)}/></label></div><p className="choice-label">How is it laid out?</p><div className="wizard-choices" role="group" aria-label="Choose layout">{layouts.map(([value,label,detail])=><button key={value} type="button" aria-pressed={layout===value} onClick={()=>setLayout(value)}><b>{label}</b><span>{detail}</span></button>)}</div><label>Ceiling height · optional<input value={height} onChange={e=>setHeight(e.target.value)} maxLength={50} placeholder="e.g. 10 ft"/></label></section>}
 {step===2&&<section className="wizard-step"><p className="eyebrow">FINALLY, THE AIRFLOW</p><h2>Select your ventilation type</h2><p>This helps frame the equipment discussion.</p><div className="wizard-choices airflow-choices" role="group" aria-label="Choose ventilation">{airOptions.map(([value,label,detail])=><button key={value} type="button" aria-pressed={ventilation===value} onClick={()=>setVentilation(value)}><b>{label}</b><span>{detail}</span></button>)}</div><label>Zones to scent · optional<input value={zones} onChange={e=>setZones(e.target.value)} maxLength={300} placeholder="e.g. reception and client lounge"/></label><p className="tiny-note">Floor area alone does not determine the machine. Layout and ventilation need review.</p></section>}
 <div className="wizard-actions">{step>0&&<button className="button outline" type="button" onClick={()=>{setStep(step-1);setResult(null);}}>← Back</button>}<button className="button" type="submit">{step===0?'Space details':step===1?'Next: airflow':'Prepare my brief'} <span>→</span></button></div></form>
 <aside className="wizard-preview"><div className="wizard-preview-image"><Image src={`/images/spaces/${current?.image||'hume-spaces-hero.png'}`} alt={`${current?.name||'Business'} setting — illustrative`} fill sizes="(max-width: 750px) 90vw, 35vw"/><span>{current?.name||'Your business'}</span></div><div className="wizard-preview-content" aria-live="polite">{result?<><p className="eyebrow">YOUR COMPLETED BRIEF</p><h3 ref={resultTitle} tabIndex={-1}>Your space brief</h3>{result.notes.map((n,index)=><p className="brief-note" key={n}><span>0{index+1}</span>{n}</p>)}<WhatsAppButton topic={`${industry} scenting. ${new URLSearchParams(result.query).get("requirements")}`} label="Send brief on WhatsApp"/><p className="tiny-note">Preliminary guidance, not a guaranteed machine recommendation.</p></>:<><p className="eyebrow">YOUR SPACE SUMMARY</p><h3>Your space details</h3><p>Describe the environment first. Then explore the equipment and scent pairing.</p><div className="brief-summary"><span>{area?`${area} sq ft`:'Area to be added'}</span><span>{hours} hours / day</span><span>{layout==='separate'?'Separate zones':layout==='mixed'?'Layout to review':'Mostly open'}</span></div><p className="tiny-note">Your answers stay in this brief until you continue to the enquiry form.</p></>}</div></aside></div>;
}



