import {JsonLd,breadcrumbData} from '@/components/StructuredData';
import WhatsAppButton from '@/components/WhatsAppButton';
import ProductGallery from '@/components/ProductGallery';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {products,referenceNotice} from '@/lib/content';
import {metadata,siteOrigin} from '@/lib/site';
export function generateStaticParams(){return products.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=products.find(p=>p.slug===slug);return p?metadata(p.name,p.description,`/equipment/${slug}`):{};}
export default async function Product({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=products.find(p=>p.slug===slug);if(!p)notFound();const images=p.slug==='800ml-commercial-diffuser'?[p.image,'800ml-commercial-diffuser-closeup.png']:[p.image];const schema={'@context':'https://schema.org','@type':'Product',name:p.name,description:p.description,brand:{'@type':'Brand',name:'HUME Spaces'},...(siteOrigin()?{url:`${siteOrigin()}/equipment/${p.slug}`,image:images.map(image=>`${siteOrigin()}/images/spaces/${image}`)}:{})};return <section className="wrap detail-section simple-product"><p className="breadcrumbs"><Link href="/shop">← All products</Link></p><div className="product-detail"><ProductGallery name={p.name} images={images}/><div><p className="eyebrow">{p.label}</p><h1>{p.name}</h1><p className="lede">{p.description}</p><dl className="spec-list"><div><dt>Coverage*</dt><dd>{p.coverage}</dd></div><div><dt>Oil capacity</dt><dd>{p.capacity}</dd></div></dl><WhatsAppButton topic={p.name} label="Get a quote on WhatsApp"/><p className="footnote">Confirm price, availability and suitability before ordering.</p><details className="simple-disclosure"><summary>Technical details</summary><p>{p.technology} · {p.controls}</p><p>* {referenceNotice}</p><WhatsAppButton topic={`${p.name}: technical specifications`}/></details><details className="simple-disclosure"><summary>Placement and installation</summary><p>{p.installation}</p><p>Confirm installation availability and charges in your quotation.</p><WhatsAppButton topic={`${p.name}: installation`}/></details><details className="simple-disclosure"><summary>Fragrance oils and support</summary><p>{p.compatibility}</p><p>Confirm approved oils, running costs and warranty terms before ordering.</p><WhatsAppButton topic={`${p.name}: fragrance oils and support`}/><Link className="text-link dark" href="/fragrance-oils">Browse fragrances →</Link></details></div></div><JsonLd data={breadcrumbData([{name:"Home",path:"/"},{name:"Products",path:"/equipment"},{name:p.name,path:`/equipment/${slug}`}])}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/></section>}



