type Section=[string,string];
type Row=[string,string,string];
function guide(slug:string,title:string,description:string,product:string,left:string,right:string,rows:Row[],sections:Section[],questions:Section[]){return {slug,title,description,product,left,right,rows,sections,questions};}
export const comparisonSources=[
 {name:'Vitruvi — Water-based diffusers',url:'https://vitruvi.com/pages/get-to-know-vitruvi-water-diffusers',summary:'Explains its ultrasonic water-based format. Specifications are product-specific.'},
 {name:'Vitruvi — Waterless diffusers',url:'https://vitruvi.com/pages/get-to-know-vitruvi-waterless-diffusers',summary:'Shows why a waterless refill is not automatically interchangeable with an ultrasonic refill.'},
 {name:'ScentAir — HVAC-connected equipment',url:'https://scentair.com/scentair-stream-diffuser',summary:'An example of purpose-built duct-connected fragrance delivery, not a specification for HUME equipment.'}
];
const machine='hume-commercial-scent-machine-pro';
const hvac='hume-hvac-scenting-system';
export const comparisonGuides=[
guide('hvac-scenting-vs-standalone-diffusers','HVAC Scenting vs Standalone Diffusers','Choose HVAC scenting when compatible ducts serve the intended zones. Consider standalone diffusers for local areas or where duct integration is unsuitable. Neither format guarantees coverage from floor area alone.',hvac,'HVAC scenting','Standalone diffusers',[
['Distribution','Reviewed air-system zones','Reviewed local placement'],['Installation','Approved duct integration','Model-specific placement and power'],['HUME example','HVAC System: ₹12,000','400ml: ₹4,190; 800ml: ₹7,950']],[
['Compare the air path','HVAC equipment is designed to work through a compatible building air system. A standalone diffuser operates from a local position. Closed rooms and separate air handlers need their own distribution decisions.'],['Check installation commitments','An HVAC proposal needs drawings, permissions and an approved connection procedure. Standalone placement still requires power, refill access and the supplied instructions. Neither should be selected solely because installation looks simple.'],['Compare running costs','Request approved oil prices and consumption assumptions for the proposed settings. Include any installation or servicing charges. Reservoir capacity does not establish a fixed monthly expense.'],['Choose for the zone','Use HVAC when the reviewed duct layout supports intended and excluded areas. Compare standalone positions for reception or isolated zones. Ask HUME to assess your floor plan before ordering.']
],[['Is HVAC always better for a large site?','No. Duct compatibility, zones and operating schedules determine suitability.'],['Can a standalone diffuser scent separate rooms?','Do not assume even distribution through partitions and closed doors.'],['What should I compare first?','The zone plan, installation responsibilities and total operating cost.']]),
guide('waterless-vs-ultrasonic-diffuser-businesses','Waterless Diffuser vs Ultrasonic Diffuser for Businesses','Waterless means no water reservoir is required by that format; ultrasonic commonly describes a water-and-vibration system. For a business, compare the exact model’s refill procedure, controls and zone fit rather than assuming waterless means commercial.',machine,'Waterless format','Ultrasonic water format',[
['Consumable','Approved oil or cartridge, depending on model','Water plus approved oil, following instructions'],['Routine','Model-specific refill and cleaning','Tank filling and cleaning per manual'],['Coverage','Exact model and airflow','Exact model and airflow']],[
['Understand the labels','Waterless describes the absence of a water-fill requirement, not one universal mechanism. Some formats use direct oil diffusion and others proprietary refills. Ultrasonic water-based models use vibrations rather than requiring a heating process.'],['Compare daily work','Ask who fills, cleans and checks equipment during business hours. Compare the actual maintenance instructions rather than assuming one category is maintenance-free. Include refill availability and storage in the decision.'],['Check liquid compatibility','Use only the refill specified for the exact machine. A waterless refill may not suit an ultrasonic device, and an ultrasonic blend should not be assumed suitable for a commercial oil machine.'],['Select on the operating brief','Give the supplier your zone area, ventilation and opening hours. HUME’s 400ml commercial format is an option to assess; this comparison does not establish an ultrasonic alternative in the HUME catalog.']
],[['Does waterless mean no maintenance?','No. Follow the supplied refill and cleaning instructions.'],['Can I move oil between both formats?','Only if the exact oil and both models explicitly permit it.'],['Which is best for a business?','Compare the actual model, approved refill, staff routine and reviewed zone fit.']]),
guide('cold-air-diffuser-vs-water-diffuser','Cold-Air Diffuser vs Water Diffuser','Compare cold-air and water diffusers by their approved consumables and operating instructions. HUME’s 400ml model lists cold-air nebulization; a water-based device has a separate filling and cleaning procedure.',machine,'Cold-air oil format','Water-based format',[
['Refill','Approved machine oil','Water and model-approved blend'],['Capacity meaning','Oil reservoir volume','Tank volume; not equivalent oil capacity'],['Setup','Confirm model instructions','Confirm water-fill instructions']],[
['Separate tank measurements','A 400ml oil reservoir and a 400ml water tank do not represent the same fragrance quantity. Read which liquid the capacity describes before comparing refill intervals.'],['Confirm the diffusion method','Cold-air nebulization and ultrasonic water diffusion are different formats. Water-based does not automatically mean heated. Ask for the exact model technology instead of inferring it from visible mist.'],['Compare staff handling','Check filling, cleaning, settings and approved liquid storage. Neither category provides a universal maintenance schedule or whole-business coverage rating.'],['Review business suitability','Measure the occupied zone and opening hours, then compare models. HUME does not publish a fixed monthly oil-use rate; request assumptions for the commercial machine before estimating costs.']
],[['Can I add water to a HUME cold-air machine?','Do not add water unless the supplied model instructions explicitly permit it.'],['Is visible mist proof of a water diffuser?','No. Use model documentation rather than appearance.'],['Do equal tank sizes mean equal refill intervals?','No. The liquids, output and operating schedules differ.']]),
guide('nebulizing-vs-ultrasonic-diffuser','Nebulizing Diffuser vs Ultrasonic Diffuser','Nebulizing and ultrasonic describe different diffusion mechanisms. Many nebulizing formats use approved oil directly, while ultrasonic water formats use a water tank; confirm the exact model instead of treating either label as a coverage guarantee.',machine,'Nebulizing format','Ultrasonic water format',[
['Mechanism','Model-specific atomization of approved oil','Vibrations in a water-based format'],['Refill','Approved machine oil','Water and approved blend'],['Sizing','Review actual output and zone','Review actual output and zone']],[
['Read the mechanism specification','HUME’s 400ml format lists cold-air nebulization. Ultrasonic water diffusers have a different tank-and-vibration arrangement. Do not infer equipment power or suitability from the technology label alone.'],['Review formulation requirements','Ask which oil is approved for the supplied model. A product sold as an essential oil or fragrance oil is not automatically compatible with either mechanism.'],['Compare operation in the property','Check controls, schedules, opening hours, cleaning and refill access. Assess the actual model in the intended zone rather than assuming one mechanism always has greater reach.'],['Choose with a full quote','Include approved liquids, delivery, taxes and support alongside machine price. HUME’s ₹4,190 commercial model is an enquiry option, not an independently tested winner over every ultrasonic product.']
],[['Does nebulizing automatically mean commercial-grade?','No. Read the exact model’s specifications and intended use.'],['Can ultrasonic diffusers operate without water?','For a water-based model, follow its water-fill instructions; do not assume waterless operation is allowed.'],['Which needs fewer refills?','Compare verified consumption and operating conditions; the mechanism alone does not answer.']]),
guide('commercial-scent-machine-vs-automatic-room-freshener','Commercial Scent Machine vs Automatic Room Freshener','Compare a commercial scent machine with an automatic room freshener using the actual delivery format, consumable and controls. An automatic dispenser may use a proprietary refill and timed release; it is not interchangeable with an oil diffuser.',machine,'Commercial oil machine','Automatic room freshener',[
['Consumable','Model-approved fragrance oil','Device-specific refill'],['Operation','Exact model controls and schedule','Exact dispenser timing and settings'],['Comparison basis','Zone fit and oil costs','Zone fit and refill costs']],[
['Identify the refill format','Automatic room freshener is a broad category. Check whether the proposed dispenser uses aerosol, cartridge or another refill. A HUME commercial oil model needs its approved liquid and instructions.'],['Compare the occupied experience','Assess the actual zone, release pattern and staff preferences. Do not assume that timed release or a commercial label creates even distribution through separate rooms.'],['Calculate consumable costs','Compare refill price, expected use and delivery charges under the same operating hours. Avoid using bottle size or dispenser price alone as a monthly-cost estimate.'],['Check support and setup','Ask about placement, power or batteries, cleaning and refill availability for both exact models. Confirm included fragrance and warranty terms before paying.']
],[['Can room-freshener refills go into a HUME machine?','No interchangeability is established. Use only the approved machine refill.'],['Does fragrance remove odours?','No odour-removal or air-treatment claim is made for HUME equipment.'],['Which is cheaper to operate?','Compare quoted consumable prices with verified usage assumptions.']]),
guide('scent-machine-vs-reed-diffuser-businesses','Scent Machine vs Reed Diffuser for Businesses','Consider a scent machine for a reviewed commercial zone and a reed diffuser for a small local corner. HUME’s Mini Reed Diffuser is passive and listed up to 120 sq ft; it is not a whole-business alternative.',machine,'Scent machine','Reed diffuser',[
['Operation','Model controls and power requirements','Passive diffusion through reeds'],['HUME listed price','400ml: ₹4,190','Mini Reed: ₹800'],['HUME listed area','400ml: 1,000–2,000 sq ft','Mini Reed: up to 120 sq ft']],[
['Match the intended area','A desk corner and an open commercial reception are different proposals. The listed HUME ranges are indicative, and neither establishes even scenting between separate rooms.'],['Compare control needs','A machine can offer model-specific operating settings. A passive reed format does not use an app or plug. Decide whether active scheduling matters for the location.'],['Keep refill liquids separate','Reed liquid is not a machine refill. Confirm the supplied fragrance, reed replacement and approved handling procedure instead of moving liquid between formats.'],['Consider the staff routine','Ask who checks liquid level, maintains equipment or replaces reeds. Compare replenishment costs and practical placement without inventing a fixed reed replacement interval.']
],[['Can reeds replace a commercial machine?','They may suit a small local corner, not an assumed whole-floor replacement.'],['Does the Mini Reed need an app?','No. It uses passive reed diffusion.'],['Can I use reed liquid in the machine?','Do not treat reed liquid as an approved machine refill.']]),
guide('room-spray-vs-commercial-scent-machine','Room Spray vs Commercial Scent Machine','Room spray is a manually applied format; a commercial scent machine is equipment operated under model-specific settings. Choose based on the intended zone, staff routine and approved product instructions.',machine,'Room spray','Commercial scent machine',[
['Operation','Manual application per label','Equipment settings per manual'],['Consumable','Approved room-spray product','Approved machine oil'],['Planning','Staff application routine','Placement and operating schedule']],[
['Compare the operating process','A spray routine depends on staff following the product label. A machine needs a suitable position, setup and an assigned operator. Neither should be treated as a substitute for ventilation or cleaning.'],['Consider consistency','Agree how the fragrance is used and how feedback is handled. Manual and equipment formats involve different routines, but this guide does not claim a universal duration or intensity advantage.'],['Separate the formulations','Room spray is not automatically suitable as a diffuser refill. Ask for the approved liquid and instructions for the exact use instead of substituting based on fragrance notes.'],['Budget the real usage','Compare expected application frequency or machine run hours with quoted consumable prices. Include equipment costs and staff responsibilities when assessing business operation.']
],[['Can I pour room spray into a machine?','No compatibility is established; use only an approved machine refill.'],['Does room spray last a fixed number of hours?','No universal duration is claimed. It depends on the product and conditions.'],['What should I choose for reception?','Review zone size, ventilation and the staff routine before comparing formats.']]),
guide('essential-oil-vs-fragrance-oil-diffuser','Essential Oil Diffuser vs Fragrance Oil Diffuser','Choose the diffuser and approved formulation as a pair. Essential oil and fragrance oil describe liquids, not universal machine compatibility; neither label guarantees safety, coverage or suitability for every business.',machine,'Essential-oil use','Fragrance-oil use',[
['Compatibility','Exact oil and model approval','Exact formula and model approval'],['Decision','Intended use and instructions','Intended use and instructions'],['Claims','No automatic health benefit','No automatic safety or performance benefit']],[
['Separate scent preference from compatibility','A fragrance you like may not be approved for the machine. Ask for the exact oil-model pairing, dilution rules if applicable and supplied handling instructions.'],['Avoid category assumptions','Do not assume that natural means appropriate for all occupants or that synthetic means unsuitable. This guide makes no hypoallergenic, therapeutic or health claim for either category.'],['Check the intended application','Ambient machine oil, reed liquid, room spray and body perfume are different uses. Approval for one application does not establish another. Confirm refill details before ordering.'],['Enquire about HUME pairing','HUME’s commercial models require approved fragrance oil. Ask which formula is supplied and what documentation is available. Do not infer compatibility with an essential oil purchased elsewhere.']
],[['Can any essential oil go into a HUME diffuser?','No universal compatibility is confirmed. Request an approved oil pairing.'],['Is fragrance oil a room spray?','Not necessarily. Check the specific intended application and formulation.'],['Does essential oil guarantee a health benefit?','No such benefit is claimed in this comparison.']]),
guide('oil-based-vs-water-based-diffuser','Oil-Based Diffuser vs Water-Based Diffuser','Oil-based and water-based labels need model-specific clarification. Compare what the tank holds, the approved refill procedure and operating demands; do not add water or substitute liquids without instructions.',machine,'Direct approved-oil format','Water-based format',[
['Tank contents','Approved oil per model','Water and approved blend per model'],['Capacity','Oil volume','Water-tank volume'],['Upkeep','Supplied oil-machine instructions','Supplied tank instructions']],[
['Clarify what oil-based means','Ask whether the term describes direct oil diffusion, a proprietary cartridge or simply the refill composition. The label alone does not identify mechanism or commercial coverage.'],['Clarify the water procedure','For a water-based device, request water-fill levels, approved blend quantities and cleaning instructions. Do not assume every water diffuser uses heat or the same technology.'],['Compare workload and costs','Review filling, cleaning, oil use, staff availability and operating hours. Similar tank volumes are not comparable consumption figures when the liquids differ.'],['Choose the approved pairing','HUME’s listed cold-air commercial format should be used according to its supplied instructions and approved oil. This page does not establish approval for adding water or replacing that oil with another format.']
],[['Can I dilute machine oil with water?','Only if the exact model and oil instructions explicitly permit it.'],['Does a 400ml water tank equal 400ml oil capacity?','No. The stated tank contents and fragrance quantities differ.'],['Which costs less each month?','A model-specific usage estimate and refill quote are required.']]),
guide('one-large-vs-multiple-small-diffusers','One Large Diffuser vs Multiple Small Diffusers','Choose machine count from the zone layout and air distribution. One large unit may be considered for an appropriate open zone; multiple smaller units may suit separate zones, but neither approach guarantees even coverage.', '800ml-commercial-diffuser','One large unit','Multiple local units',[
['Planning','One reviewed distribution area','Separate reviewed zones'],['Operation','One refill and settings location','Coordinated settings and refills'],['Risk to assess','Unserved separated areas','Overlapping intensity and more upkeep']],[
['Map zone boundaries','Mark walls, closed doors and independent air systems. Total floor area alone does not establish whether one position can serve the property or whether each room needs equipment.'],['Compare distribution proposals','Ask the supplier to show proposed positions and intended reach for either arrangement. A larger reservoir is not evidence of greater distribution; the HUME 400ml and 800ml models both list coverage reaching 2,000 sq ft.'],['Compare maintenance responsibilities','Multiple units introduce more refill and settings locations. One unit concentrates operation at one position but may not serve isolated areas. Include staff time, consumables and support in the comparison.'],['Test before scaling','Review a defined zone and gather feedback before ordering a property-wide quantity. Coordinate settings to avoid overlapping intensity, and retain areas that should remain unscented.']
],[['Does two units mean double coverage?','No. Layout, overlap and airflow must be reviewed.'],['Is the 800ml model twice as powerful as 400ml?','Capacity does not establish comparative output or power.'],['How should I request a machine count?','Send a floor plan with zone areas, partitions, height and ventilation.']]),
guide('hvac-vs-wall-mounted-scent-machine','HVAC Scenting vs Wall-Mounted Scent Machine','HVAC describes an air-system connection; wall-mounted describes a physical mounting arrangement. They are not necessarily opposite technologies. Compare approved mounting and distribution for the exact model.',hvac,'HVAC-connected format','Wall-mounted arrangement',[
['Term describes','Fragrance distribution connection','Physical placement'],['Approval','Duct and model compatibility','Model mounting specification'],['HUME status','Separate HVAC format listed','Wall-mount approval needs confirmation']],[
['Compare equivalent specifications','An HVAC unit could have a model-specific mounting arrangement, while a wall-mounted unit may diffuse locally. Ask how each proposed device delivers fragrance rather than assuming mounting decides distribution.'],['Verify mounting documentation','Request approved brackets, orientation, power and clearances. HUME’s catalog does not confirm wall-mount approval for its commercial models; a compact photo is not installation evidence.'],['Review the air path','An HVAC proposal needs duct zoning and schedules. A local mounted proposal needs a reviewed occupied zone and placement. Neither provides a whole-building guarantee from a square-foot figure alone.'],['Request a documented design','Ask for the exact model manual, proposed position, connection responsibilities and refill access. Confirm installer availability and costs separately from HUME’s ₹12,000 HVAC equipment listing.']
],[['Can an HVAC unit be wall-mounted?','It depends on the exact model’s approved installation arrangement.'],['Is a wall-mounted model automatically HVAC-compatible?','No. Mounting and duct compatibility are separate specifications.'],['Are HUME wall-mounted options confirmed?','No wall-mount approval is confirmed in the current catalog.']]),
guide('commercial-vs-home-aroma-diffuser','Commercial Diffuser vs Home Aroma Diffuser','Compare commercial and home diffusers using verified specifications and operating conditions. The category name alone does not establish output, reliability or suitability for a business.',machine,'Commercial-labeled model','Home-labeled model',[
['Sizing','Verify exact model and zone','Verify exact model and zone'],['Operation','Compare business-hours routine','Check suitability for intended hours'],['Purchase','Ask for support and refills','Ask for support and refills']],[
['Check the actual intended use','Read coverage, controls, refill instructions and permitted operation for each model. A home product should not be assumed suitable for a full commercial shift; a commercial label alone is not proof of suitability.'],['Measure the business zone','Provide area, ceiling height and airflow along with opening hours. Do not treat a room demonstration as evidence for a large reception, gym or showroom.'],['Compare ownership needs','Ask about consumable availability, cleaning, refill access and written warranty terms. Establish staff responsibilities and total cost rather than choosing only by reservoir volume.'],['Review a priced HUME option','The 400ml Commercial Diffuser is listed at ₹4,190 with indicative 1,000–2,000 sq ft coverage. Use this as a shortlist specification for review, not a guarantee or an independently tested advantage over home models.']
],[['Can a home diffuser work in an office?','Possibly for a suitable local use, but verify the exact model and operating conditions.'],['Does commercial mean maintenance-free?','No. Follow supplied operation, cleaning and refill instructions.'],['What should I compare beyond price?','Approved liquids, zone fit, controls, upkeep and written support terms.']]),
guide('cold-air-diffusion-vs-heat-diffusion','Cold-Air Diffusion vs Heat Diffusion','Cold-air and heat diffusion use different operating mechanisms. Compare the approved formulation, placement and model instructions; do not confuse an ultrasonic water diffuser with a heated device.',machine,'Cold-air format','Heat-based format',[
['Mechanism','Listed cold-air atomization format','Model uses heat for fragrance release'],['Instructions','Approved machine oil and setup','Approved product and heat-device setup'],['Comparison','Actual output and zone','Actual output and zone']],[
['Read the technology description','HUME’s 400ml model lists cold-air nebulization. A heat-based device uses a different release mechanism. Water-based ultrasonic equipment can operate using vibrations, so water does not imply heat.'],['Verify formulation and placement','Ask what liquids or materials the exact model permits and follow its positioning instructions. Do not transfer a fragrance between heated and cold-air devices without explicit approval.'],['Avoid unsupported superiority claims','This guide does not claim that every cold-air product outperforms every heated product or that either technology creates a health benefit. Evaluate the supplied specifications and intended use.'],['Compare the business routine','Review operating hours, controls, refill procedure, maintenance and staff responsibilities. Select for the zone and approved setup, then confirm the quote’s inclusions and support.']
],[['Are ultrasonic diffusers heated?','Water-based ultrasonic formats can use vibrations rather than heat; verify the model.'],['Can heat-device fragrance go into HUME equipment?','No compatibility is established. Use approved machine oil.'],['Does cold-air mean a guaranteed refill interval?','No. Refill timing depends on output, hours and model-specific consumption.']]),
guide('signature-scent-vs-standard-fragrance-businesses','Signature Scent vs Standard Fragrance for Businesses','A standard fragrance can provide a consistent brand experience. A commissioned signature scent may involve development and formula rights; the phrase signature scent does not automatically establish exclusivity.', 'hume-pro-commercial-tower','Commissioned signature scent','Standard catalog fragrance',[
['Selection','Creative brief and approval process','Choose an existing approved option'],['Rights','Contract-specific ownership and exclusivity','Do not assume exclusive rights'],['HUME scope','Bespoke development requires confirmation','Fragrance concepts available for discovery']],[
['Define the creative requirement','Decide whether an existing approved fragrance meets the space’s atmosphere or whether you require a new formula. Describe brand identity, audience, excluded notes and diffusion format in the brief.'],['Compare approval effort','Custom development may include samples, revisions and production terms. Catalog selection still benefits from testing in the intended zone. Confirm fees, minimum orders and lead times rather than assuming either process is immediate.'],['Clarify formula rights','Ownership, licensing and exclusivity depend on the written agreement. Consistently using a catalog fragrance does not make the formula exclusive. Ask how future reorders and changes are controlled.'],['Check HUME’s current offer','HUME provides fragrance discovery and equipment enquiry. Bespoke development and exclusivity are not confirmed standard services. The featured Tower is an equipment option, not proof of a custom-fragrance service.']
],[['Does signature mean exclusive?','No. Exclusivity must be defined in a contract.'],['Can a catalog fragrance represent a brand?','It can be chosen consistently, but that does not establish ownership or exclusivity.'],['Does HUME offer custom scent development?','Enquire before assuming availability, formula rights or development terms.']]),
guide('buying-scent-machine-vs-managed-scenting-service','Buying a Scent Machine vs Managed Scenting Service','Buying equipment gives the business responsibility for operation unless extra services are agreed. A managed arrangement should specify consumables, visits, fault response and contract terms. Compare full scope and first-year cost.',machine,'Equipment purchase','Managed service proposal',[
['Responsibility','Business operates unless agreed otherwise','Contract defines provider responsibilities'],['Costs','Equipment plus refills and agreed services','Recurring fees and stated inclusions'],['HUME scope','Priced equipment catalog','Managed contract requires confirmation']],[
['Understand what ownership includes','A machine purchase does not automatically include installation, oil or maintenance visits. Assign an operator and request approved refill and setup instructions. Confirm written warranty and delivery terms.'],['Read managed-service deliverables','Ask about equipment ownership, consumable quantities, visit frequency, fault response and extra-zone charges. A managed label is not evidence that all operating work is included.'],['Compare the same time period','Calculate first-year hardware, installation, oil, freight and agreed service costs against the contract’s fees and exclusions. Include cancellation, renewal and equipment-return conditions when reviewing the service proposal.'],['Choose for internal capacity','A business able to handle settings and inventory may consider equipment ownership. A multi-site programme may need additional coordination. HUME’s managed-service availability requires confirmation before choosing a contract model.']
],[['Does buying include monthly refills?','Only if the quote explicitly includes them; no such inclusion is assumed.'],['Who owns equipment under a managed service?','The contract must specify ownership and end-of-term arrangements.'],['Does HUME have a managed subscription?','It is not a confirmed standard offer; enquire about available scope for your property.']])
];
