import {buyerGuides} from './buyer-guides';
import {additionalPlaces} from './places';
export const products = [
 {slug:'hume-commercial-scent-machine-pro',price:4190,name:'400ml Commercial Diffuser',label:'Standalone scent machine',image:'commercial-scent-machine-pro.jpg',capacity:'400 ml',coverage:'1,000–2,000 sq ft',technology:'Cold-air nebulization',controls:'App control',description:'A standalone format to explore for reception areas, gym floors and commercial interiors.',compatibility:'The reference lists concentrated spatial oils. The exact approved formula, viscosity and refill instructions need confirmation.',installation:'Placement, mounting options, power requirements and commissioning must be confirmed before ordering.'},
 {slug:'hume-pro-commercial-tower',price:9650,name:'Tower Commercial Diffuser',label:'Tower scent machine',image:'commercial-diffuser.png',capacity:'500 ml',coverage:'Up to 1,500 sq ft',technology:'Cold-air nebulization',controls:'Bluetooth app · multiple schedules',description:'A tower format to consider for hotel lobbies, boutiques and showrooms where equipment sits within the interior.',compatibility:'Approved oil compatibility and refill instructions must be confirmed for this model.',installation:'Review a suitable position with airflow, guest circulation and access for refilling in mind. Mounting and electrical specifications are pending.'},
 {slug:'hume-hvac-scenting-system',price:12000,name:'HVAC Scenting System',label:'Duct-connected format',image:'hvac-diffuser-v2.png',capacity:'1,000 ml',coverage:'Up to 5,000 sq ft',technology:'Duct air nebulization',controls:'HVAC direct · multi-zone reference',description:'A duct-connected format for discussion where a property has central air distribution.',compatibility:'Oil formula and duct-system compatibility require a technical review; central air conditioning alone does not establish suitability.',installation:'Share the HVAC layout and air-handler details. Installation availability, duct connection and zoning need confirmation.'},
 {slug:'hume-mini-reed-diffuser-50ml',price:800,name:'Mini Reed Diffuser',label:'Passive fragrance · small areas',image:'decorative-diffuser.png',capacity:'50 ml',coverage:'Up to 120 sq ft',technology:'Passive reed diffusion',controls:'No app control listed',description:'A compact glass format to explore for desks, powder rooms and small guest areas.',compatibility:'A reed fragrance is not a machine refill. Confirm the supplied fragrance and replacement instructions.',installation:'A stable surface and suitable placement are required. Keep away from spill-sensitive finishes; follow the supplied instructions.'}
 ,{slug:'800ml-commercial-diffuser',price:7950,name:'800ml Commercial Diffuser',label:'Commercial scent machine',image:'800ml-commercial-diffuser.png',capacity:'800 ml',coverage:'Up to 2,000 sq ft',technology:'Pending confirmation',controls:'Pending confirmation',description:'A commercial diffuser with an 800 ml fragrance oil capacity and listed coverage up to 2,000 sq ft. Suitability depends on layout and airflow.',compatibility:'Confirm the approved fragrance oil and refill instructions for this model before use.',installation:'Confirm placement, power requirements, mounting options and installation instructions before ordering.'}
,{slug:'car-room-diffuser',price:1190,name:'Car & Room Diffuser',label:'Personal spaces',image:'car-room-diffuser.png',capacity:'Confirm capacity',coverage:'Cars, cabins & small rooms',technology:'Confirm diffusion technology',controls:'Confirm controls',description:'A compact diffuser for cars, office cabins and small rooms, priced at ₹1,190.',compatibility:'Confirm the approved refill, supplied fragrance and usage instructions for this model.',installation:'Follow the supplied placement instructions. Confirm vehicle compatibility and power requirements before use.'}
] as const;
export const scents = [
 {name:'Ivory Lobby',family:'Citrus · tea · woods',notes:'Bergamot, white tea, cedar',mood:'Polished and welcoming',color:'#d6cabb'},
 {name:'Santal Residence',family:'Soft woods · amber',notes:'Sandalwood, iris, amber',mood:'Warm and understated',color:'#bea78e'},
 {name:'Verdant Courtyard',family:'Green · aromatic',notes:'Neroli, fig leaf, vetiver',mood:'Airy and green',color:'#9aa691'},
 {name:'Midnight Suite',family:'Floral · woody',notes:'Saffron, rosewood, soft oud',mood:'Intimate and distinctive',color:'#9b8580'},
 {name:'Coastal Gallery',family:'Mineral · fresh woods',notes:'Mineral air, sage, pale woods',mood:'Fresh and restrained',color:'#aab9b5'},
 {name:'Quiet Library',family:'Tea · leather · woods',notes:'Black tea, suede, cedar',mood:'Composed and woody',color:'#a99d89'}
];
export const industries = [
 {slug:'hotels',name:'Hotels & hospitality',short:'Hotels',image:'hotels-app.jpg',intro:'Scenting for hotels',description:'A lobby, corridor and spa have different airflow, operating hours and guest needs. Describe each zone before choosing equipment.',zones:['Lobby & reception','Guest corridors','Spa reception'],considerations:['Record lobby ceiling height, entrance traffic and air-conditioning hours.','Consider guest preferences and retain unscented areas.','Keep fragrance away from dining and food preparation.'],equipment:[0,1,2]},
 {slug:'gyms',name:'Gyms & fitness studios',short:'Gyms',image:'gyms-app.png',intro:'Scenting for gyms',description:'Open workout floors, changing areas and reception need separate consideration. Fragrance should complement a clean, ventilated space.',zones:['Reception','Workout floor','Studio entrance'],considerations:['Explain fresh-air ventilation, extraction and peak occupancy.','Scenting does not replace cleaning or ventilation and is not an odour-removal claim.','Discuss member sensitivities and keep enclosed activity areas lightly scented or unscented.'],equipment:[0,1]},
 {slug:'offices',name:'Offices & workplaces',short:'Offices',image:'receptions-app.jpg',intro:'Scenting for offices',description:'Begin with reception and client lounges. Work areas require a conversation about staff preferences, shared air and unscented alternatives.',zones:['Reception','Client lounge','Meeting-room entrance'],considerations:['Discuss fragrance preferences with the people who use the space every day.','Map separate rooms and shared air distribution before choosing one system.','Share building-management requirements and operating hours.'],equipment:[0,2]},
 {slug:'retail',name:'Retail & showrooms',short:'Retail',image:'retail-stores-app.jpg',intro:'Scenting for retail and showrooms',description:'Think about entrance airflow, customer movement and merchandise when planning fragrance for a boutique or showroom.',zones:['Store entrance','Display gallery','Customer lounge'],considerations:['Describe frequent door opening and the distance between display areas.','Keep fragrance away from food and scent-sensitive merchandise.','Allow access for oil changes without interrupting the customer journey.'],equipment:[0,1]},
 {slug:'spas',name:'Spas & wellness',short:'Spas',image:'resorts-app.jpg',intro:'Scenting for spas',description:'Reception and waiting areas can have different needs from treatment rooms. Account for treatment products, guest preferences and ventilation.',zones:['Reception','Waiting lounge','Transition areas'],considerations:['Avoid competing with products used during treatments.','Discuss guest sensitivities and retain unscented treatment options.','Review enclosed rooms independently from open reception.'],equipment:[1,3]},
 ...additionalPlaces
];
export const guides = [
 ...buyerGuides,
 {slug:'choosing-a-scent-machine',title:'How to choose a commercial scent machine',description:'Coverage is a starting point. Airflow, layout and operation complete the brief.',sections:[['Measure your space','Record floor area, ceiling height, the number of rooms and any open connections. A listed square-foot range does not guarantee even coverage in your property.'],['Check ventilation and airflow','Explain whether the space uses split AC, central ducts, fresh-air ventilation or extraction. Share how often doors open and whether the HVAC runs whenever scenting is needed.'],['Compare equipment formats','Explore standalone equipment for a local zone and a duct-connected format only after HVAC compatibility is reviewed. Compare the 400ml Commercial Diffuser, Tower Commercial Diffuser and HVAC formats in the equipment catalog.'],['Verify specifications before ordering','Ask for approved specifications, oil compatibility, electrical requirements, placement instructions and the support available in your city.']]},
 {slug:'equipment-and-oil-costs',title:'Planning equipment and ongoing oil costs',description:'What to include in a quote, and why there is no fixed monthly estimate yet.',sections:[['Separate equipment from running costs','Request equipment pricing, taxes, delivery and any installation-related charges as separate line items. Public prices are pending approval.'],['Ask about oil consumption','Oil use depends on output settings, operating hours, formula, airflow and layout. Tank capacity is not a refill interval. No verified consumption rates are available for these products.'],['Compare oil prices and usage estimates','Ask for the oil pack size and price, compatibility, expected consumption assumptions and replacement parts. Compare estimates using the same operating schedule.'],['Confirm support and warranty terms','Confirm guidance, troubleshooting, maintenance responsibilities and warranty terms in the quotation. Recurring refill plans and managed services are possible future offers, not current commitments.']]},
 {slug:'fragrance-and-compatibility',title:'Choosing a fragrance for your business',description:'Use the scent profile as a conversation starter, then verify the oil and equipment pairing.',sections:[['Choose a scent profile','Citrus and tea, soft woods, green notes and mineral profiles offer different starting points. The existing HUME library contains six concepts; stock, samples and final formulas are not confirmed.'],['Consider the space and its users','Describe the materials, nearby food or treatment products and how long people stay in the area. Ask about guest and staff preferences rather than choosing solely from a fragrance name.'],['Confirm oil and machine compatibility','Do not treat perfume, reed liquid or essential oil as a universal machine refill. Ask for the approved formula and instructions for the exact machine.'],['Choose intensity and unscented areas','Plan a restrained setting and unscented alternatives. No hypoallergenic, therapeutic, odour-neutralising or certification claims have been verified.']]}
];
export const faqs = [
 ['Which machine suits my space?','Start with area, ceiling height, layout, ventilation and operating hours. The selector prepares a brief for review; it does not calculate a guaranteed machine recommendation.'],
 ['Are the coverage figures guaranteed?','No. These are specifications listed in the existing HUME reference and are pending supplier confirmation. Actual suitability depends on room volume, airflow and zoning.'],
 ['How much will equipment and oil cost?','Request an itemised quotation. Equipment prices and oil pack prices are pending approval, and no verified consumption rate is available for a monthly estimate.'],
 ['Do you offer installation, maintenance or a warranty?','Availability, responsibilities and terms must be confirmed in your quotation. This website does not promise installation, maintenance visits or a warranty.'],
 ['Can I subscribe to refills or managed scenting?','Those are potential future offers. The launch site supports equipment and fragrance discovery and consultation requests.'],
 ['Can I use any fragrance oil?','No universal compatibility is established. Confirm the approved formula, viscosity and instructions for your specific machine before adding oil.'],
 ['Are fragrance samples available?','Sample availability and trial arrangements need confirmation. Include your preferred scent direction in your enquiry.']
];
export const referenceNotice = 'Specifications from the existing HUME catalog; pending confirmation. Coverage is indicative and depends on layout, ceiling height and airflow.';




