type Section=[string,string];
function guide(slug:string,title:string,description:string,sections:Section[],questions:Section[]){return {slug,title,description,product:'hume-hvac-scenting-system',sections,questions};}
export const hvacSources=[
 {name:'ScentAir Stream — HVAC-connected format',url:'https://scentair.com/scentair-stream-diffuser',summary:'An example of purpose-built HVAC fragrance delivery with scheduling and intensity controls. Its specifications apply to that product, not to HUME equipment.'},
 {name:'ScentAir — Existing HVAC integration',url:'https://help.scentair.com/en-US/can-scent-marketing-integrate-with-existing-hvac-systems-5599357',summary:'Describes systems designed for integration with existing infrastructure; suitability still requires a model and building review.'}
];
export const hvacGuides=[
guide('what-is-hvac-scenting','What Is HVAC Scenting and How Does It Work?','HVAC scenting uses purpose-built fragrance equipment connected to a compatible air-distribution system. Moving air carries fragrance to the zones served by that system; actual distribution depends on duct layout and operation.',[
['Understand the equipment and air path','HVAC stands for heating, ventilation and air conditioning. In an HVAC-connected scenting arrangement, a compatible diffuser introduces fragrance through a manufacturer-approved connection. The system uses the building’s airflow rather than assuming a local machine scents every room.'],['Separate diffusion from air treatment','Fragrance changes the scent experience of an occupied space. It should not be presented as cleaning, ventilation, disinfection or air purification. Existing HVAC maintenance and fresh-air requirements remain separate responsibilities.'],['Review the zones receiving air','Identify which spaces share an air handler and which use separate systems. Mark areas to leave unscented. A connection serving reception may also affect adjacent spaces, so review distribution boundaries before installation.'],['Explore the HUME HVAC format','HUME lists a 1,000ml HVAC Scenting System at ₹12,000 with indicative coverage up to 5,000 sq ft. Confirm the exact model, approved oil, controls and installation scope before considering it for your property.']
],[['Does HVAC scenting require ducts?','A duct-connected proposal requires a compatible air-distribution system; do not assume split AC is suitable.'],['Does it scent every room automatically?','No. Distribution follows the actual air system and reviewed zones.'],['Does it purify air?','No air-purification or disinfection claim is made for HUME scenting equipment.']]),
guide('connect-scent-diffuser-central-ac','How to Connect a Scent Diffuser to Central AC','Connecting a diffuser to central AC requires the exact model’s installation instructions and an HVAC compatibility review. Have the approved installer identify the connection and commissioning procedure; there is no universal connection point.',[
['Collect the required documents','Obtain the diffuser manual, approved accessories, electrical requirements and duct drawings. Share air-handler locations, schedules and intended scenting zones with the installer. Central AC alone does not establish compatibility.'],['Agree the installation design','Ask the installer to identify the approved connection point, equipment position and refill access for the supplied model. Record building-management approval and responsibilities before work begins. Do not use another brand’s diagram as HUME instructions.'],['Coordinate installation and commissioning','The approved installer should follow the manufacturer’s procedure, check the connection and review operation with building airflow. Confirm how operation is paused when the relevant air system is off. Hardware or software interlocks must be verified, not assumed.'],['Approve operation before rollout','Start with the agreed restrained settings and review feedback in intended and excluded zones. Keep the installed configuration, approved fragrance and operating schedule documented for maintenance and future changes.']
],[['Can I connect any diffuser to AC?','No. The exact model must support an approved HVAC connection.'],['Where should I drill the duct?','This guide does not specify a drill point. The approved manual and HVAC installer must determine it for the actual system.'],['Does HUME provide an installation service?','Availability, responsibility and charges require confirmation in your written quote.']]),
guide('fragrance-machine-connected-hvac','Can a Fragrance Machine Be Connected to HVAC?','Some fragrance machines are designed for HVAC integration; others are standalone only. Confirm explicit manufacturer approval and the building’s compatibility before connecting a machine to ducts.',[
['Check the exact model','Ask for a specification or manual that permits HVAC integration. A bottle size, strong mist or commercial label does not establish that a machine can be duct-connected.'],['Verify the building conditions','Provide the air-handler and duct layout, operating hours and target zones. Ask the reviewer to identify shared-air areas and permissions needed for a connection.'],['Confirm supporting components','Check approved connection accessories, electrical supply, placement and maintenance access. Do not assume a standalone model can become an HVAC unit through a generic tube or adaptor.'],['Compare HUME’s listed formats','HUME has a separately listed HVAC Scenting System. Its standalone 400ml, 800ml and Tower options should not be treated as approved HVAC-connected models without specific confirmation.']
],[['Are all commercial scent machines HVAC-compatible?','No. Compatibility is model-specific.'],['Can HUME’s 800ml model connect to ducts?','HVAC approval for that model is not confirmed in the catalog. Enquire for exact documentation.'],['What should I request before purchase?','The exact model manual, approved connection details and a building compatibility review.']]),
guide('best-scent-diffuser-centralised-air-conditioning','Best Scent Diffuser for Centralised Air Conditioning','The best diffuser for centralised air conditioning is a purpose-built model that fits the building’s air-handler zoning, controls and maintenance needs. Choose on documented compatibility rather than floor area alone.',[
['Match the air system first','List air handlers, supplied spaces and schedules. Identify whether the target area is a whole served zone or only one portion. Ask for a compatible design before comparing equipment prices.'],['Compare operating capabilities','Ask about scheduling, intensity adjustment and coordination with HVAC operation. Verify these features for the exact supplied model. Another brand’s app or interlock capability does not establish HUME specifications.'],['Review HUME’s HVAC option','The listed HUME HVAC unit is ₹12,000 with a 1,000ml reservoir and indicative coverage up to 5,000 sq ft. Controls and installation details need confirmation. It is a starting point for technical enquiry, not a universal central-AC recommendation.'],['Evaluate the complete proposal','Request approved oil, connection responsibilities, power requirements, consumption assumptions and written support terms. Ask which areas will remain unscented and how changes to HVAC schedules will be handled.']
],[['Is the highest coverage model best?','Not necessarily. Distribution, compatibility and operation matter alongside the listed area.'],['Does HUME’s HVAC model have app controls?','App and operating interfaces require confirmation for the supplied HVAC model.'],['What if my AC has multiple air handlers?','Review each served zone and handler; do not assume one connection covers all of them.']]),
guide('scent-entire-building-through-hvac','How to Scent an Entire Building Through HVAC','Whole-building HVAC scenting begins with an air-system and zoning plan. Multiple air handlers, separate rooms and excluded areas may require different equipment decisions; one connection does not guarantee building-wide distribution.',[
['Define the intended coverage','Map reception, corridors, offices and tenant spaces separately. Exclude areas where fragrance is unwanted. Total floor area includes spaces that may not belong in the scenting proposal.'],['Map air distribution','Identify which zones share supply and return air and which have independent systems. Share this information with the technical reviewer. Distribution should be assessed against the actual building drawings.'],['Plan equipment by reviewed zone','Ask for a justified equipment count, proposed connections and operating schedules. Do not multiply listed coverage to create a guarantee. HUME does not list a single model verified for an arbitrary whole-building area.'],['Roll out in stages','Evaluate a defined zone, review feedback and oil use, then consider expansion. Document the approved configuration and manage later changes to tenants, ventilation and schedules through the same review process.']
],[['Can one HVAC unit scent an entire building?','Not automatically. It depends on the air systems, zones and approved equipment configuration.'],['Should every building area be scented?','No. Establish intended and excluded areas, accounting for occupants and building policies.'],['Will two 5,000 sq ft units cover 10,000 sq ft?','That arithmetic does not establish compatibility or even distribution; zoning review is required.']]),
guide('hvac-scenting-system-cost-india','HVAC Scenting System Cost in India','HUME’s listed HVAC Scenting System equipment price is ₹12,000. A complete project quote should separately confirm GST, delivery, installation, approved fragrance oils and ongoing support; no fixed installed or monthly cost is published.',[
['Separate equipment from project cost','The ₹12,000 listing is for the equipment. Do not assume it includes connection accessories, contractor work, fragrance or taxes. Ask for an itemised quote for your city and building.'],['Request installation line items','Clarify technical review, mounting, power, duct connection and commissioning responsibilities. Some work may require the building’s existing HVAC contractor. Confirm availability and charges before ordering.'],['Budget ongoing fragrance use','Request approved oil prices, pack sizes and consumption assumptions based on operating hours and settings. A 1,000ml reservoir does not establish a one-month refill interval or fixed monthly expense.'],['Compare proposals on the same basis','Give each supplier the same zone brief and compare first-year equipment, installation, refill and support costs. Record assumptions and exclusions so a lower headline price does not hide required work.']
],[['What is the HUME HVAC machine price?','The listed equipment price is ₹12,000; confirm GST, delivery and inclusions.'],['Is installation included?','It is not confirmed as included. Request an itemised quote and written responsibilities.'],['What is the monthly oil cost?','No verified fixed monthly cost is published; it depends on approved oil pricing and actual consumption.']]),
guide('where-hvac-scent-diffuser-installed','Where Is an HVAC Scent Diffuser Installed?','An HVAC diffuser is installed at a location approved for its model and the building’s air system. The equipment position and fragrance connection point are separate decisions requiring installation documentation.',[
['Identify the two positions','The machine needs an approved equipment location, while its fragrance delivery connection must suit the duct or air-handler design. Do not infer either position from the visible outlet grille in an occupied room.'],['Use the correct manual','Approved orientation, connection accessories, clearances and access vary by equipment. Have the installer review the supplied documentation rather than copying a location from another brand’s installation.'],['Keep servicing accessible','Consider power, approved mounting, oil replacement and inspection access. Ask who can reach the equipment and when servicing can occur without disrupting building operations.'],['Review the served spaces','The connection location affects which zones are considered in the proposal. Mark excluded areas and confirm the air path with the HVAC reviewer before approving the design.']
],[['Is the machine installed inside the air handler?','Placement is model-specific. Do not assume an inside or outside position without approved instructions.'],['Can it be placed beside an AC vent?','A nearby position alone does not establish an approved HVAC connection.'],['Where should HUME’s unit be placed?','Request the actual model manual and a building-specific installation review.']]),
guide('add-scenting-existing-hvac-system','Can Scenting Be Added to an Existing HVAC System?','Scenting can be considered for an existing HVAC system when the diffuser supports integration and the building’s ducts, zoning and operation are suitable. A retrofit needs technical approval, not just spare space near an air handler.',[
['Review existing infrastructure','Share system drawings, air-handler schedules and the spaces currently served. Include building-management restrictions and known maintenance or airflow issues before discussing fragrance equipment.'],['Check model compatibility','Ask for the approved connection arrangement and operating conditions for the supplied model. Existing ducts do not mean every scent machine can be connected to them.'],['Coordinate a retrofit plan','Agree who approves and performs the work, what access is needed and how the system will be checked afterward. Confirm warranty implications with the relevant equipment providers and building contractor.'],['Choose an alternative when needed','If the system cannot serve the intended zone appropriately, consider a standalone local-zone proposal. A retrofit should not be forced simply because the property already has central air.']
],[['Does retrofit mean replacing the AC?','Not necessarily; feasibility and required work depend on the approved integration and existing system.'],['Can any existing building accept scenting?','No. Technical constraints, policies and occupant preferences can make scenting inappropriate.'],['Who should assess the retrofit?','The diffuser supplier and the building’s authorised HVAC reviewer or contractor should coordinate the design.']]),
guide('hvac-scenting-hotels-guide','HVAC Scenting for Hotels: Complete Guide','Hotel HVAC scenting should begin with lobby and common-area zoning, guest preferences and air-handler review. Keep guest rooms, dining areas and spa spaces as separate decisions rather than assuming one hotel-wide fragrance plan.',[
['Map hotel guest areas','Separate lobby, reception, corridors and lounges. Identify connections to guest floors and food-service spaces. Ask which air handlers serve each zone and where shared return air may affect excluded areas.'],['Agree fragrance and guest response','Evaluate an approved fragrance at a restrained setting. Collect feedback from reception staff and management, and define a process for responding to guest objections. Retain unscented options where feasible.'],['Coordinate engineering and operations','Involve the hotel’s engineering team in connection review and housekeeping or reception in refill responsibility. Match operation to the relevant air system and occupied hours. Verify controls rather than assuming app support.'],['Compare the hotel proposal','Ask for equipment by zone, approved oil, installation responsibilities and support terms. The HUME HVAC price is an equipment starting point; it does not establish a complete hotel service package.']
],[['Will lobby scenting reach guest rooms?','Shared air systems may affect other spaces; review the actual air path rather than assuming separation.'],['Should dining areas share the fragrance?','Treat food-service zones separately and keep them outside a general ambient scenting proposal.'],['Does HUME guarantee hotel-wide coverage?','No. Compatibility, zoning and service scope require confirmation.']]),
guide('hvac-scenting-shopping-malls','HVAC Scenting for Shopping Malls','Mall HVAC scenting requires tenant-aware zoning and air-handler coordination. Concierge areas, lounges, shops and food courts should not be treated as one simple coverage calculation.',[
['Separate shared and tenant areas','Map enclosed concierge areas, circulation and independent stores. Record which air systems serve each. Tenant fragrance and lease or building policies need consideration before a shared scenting plan.'],['Account for mall geometry','Atriums, high ceilings and frequently opened entrances differ from standard rooms. Include height and ventilation details in the proposal instead of relying on total mall square footage.'],['Protect food and excluded zones','Identify food courts, preparation, storage and other areas outside the general fragrance proposal. Ask the technical reviewer whether shared air could cross those boundaries.'],['Plan approvals and rollout','Coordinate facilities management, tenant requirements and contractor access. Begin with an approved defined zone and review feedback and consumption before extending the plan.']
],[['Can one machine scent a whole mall?','No whole-mall assumption is supported by HUME’s listed coverage; review independent systems and zones.'],['Does a large atrium fit a floor-area rating?','Height and airflow need assessment alongside floor area.'],['What should a mall quote include?','A zone map, air-system review, equipment schedule, exclusions, operating assumptions and itemised costs.']]),
guide('hvac-scenting-large-offices','HVAC Scenting for Large Offices','Large-office HVAC scenting should respect staff preferences, shared air and separate meeting rooms. Consider selected reception or client zones first instead of assuming fragrance belongs throughout the workplace.',[
['Define the office’s scenting policy','Discuss fragrance preferences with people who work in the space all day. Identify unscented areas and a feedback process before purchasing equipment. A client-lounge objective is different from scenting all workstations.'],['Review the air-system boundaries','Map reception, meeting rooms and open-plan areas against air handlers and schedules. Closed doors do not necessarily establish separate air distribution. Ask the technical reviewer to assess the selected zones.'],['Coordinate daily operation','Assign responsibility for settings, refills and complaints. Match operation to occupancy and the relevant air system. Check how evening meetings or partial-floor operation affect the plan.'],['Request an office-specific proposal','Provide floor plans, headcount patterns, operating hours and excluded areas. Ask for a reviewed equipment count and running-cost assumptions. Do not infer productivity or health benefits from fragrance.']
],[['Does scenting improve staff productivity?','No productivity or health benefit is guaranteed in these guides.'],['Can only reception be scented?','Potentially, if the air-system zoning supports the intended boundary; technical review is needed.'],['What about staff who dislike fragrance?','Include feedback and unscented options in the workplace policy and operating decision.']]),
guide('hvac-scenting-banquet-halls','HVAC Scenting for Banquet Halls','Banquet-hall HVAC scenting needs event-specific scheduling, high-volume-space review and separation from food service. Evaluate the actual hall configuration and guest use before selecting a system.',[
['Measure the event configuration','Record hall dimensions, ceiling height and movable partitions. A divided event layout can have different air-distribution needs from the same hall opened for a large function.'],['Separate food and fragrance planning','Include buffet, dining, kitchen and storage boundaries in the review. Existing food aromas and shared air should inform whether scenting is appropriate. Do not assume an entire banquet venue should receive fragrance.'],['Plan changing schedules','Events vary in duration, occupancy and ventilation operation. Assign an operator and agree a restrained setting for the approved zones. Verify how the supplied equipment can be scheduled or paused.'],['Review technical and commercial scope','Ask for a connection plan, installation responsibilities, refill access and consumption estimate based on event hours. The HUME HVAC listing is not a guarantee of coverage for a high-ceiling banquet hall.']
],[['Can the 5,000 sq ft rating be used for a tall hall?','Do not assume so. Ceiling height, partitions and airflow require a separate review.'],['Should fragrance operate during dining?','Food-service conditions need a separate suitability decision; keep food areas outside the general proposal.'],['How should event usage be quoted?','Use expected operating hours and settings rather than assuming a fixed monthly consumption.']]),
guide('hvac-scent-system-fragrance-oil-consumption','How Much Fragrance Oil Does an HVAC Scent System Consume?','HVAC fragrance-oil consumption depends on the supplied model, output setting and operating hours. HUME has no verified fixed consumption rate for its HVAC model; reservoir capacity alone cannot establish monthly usage.',[
['Separate reservoir size from usage','The listed HUME HVAC reservoir is 1,000ml. That describes how much it holds, not how quickly oil is used or how long a refill lasts. Ask for a model-specific estimate under your operating conditions.'],['Record a measured baseline','Keep a log of approved oil added, remaining quantity, settings and actual run hours. Use the supplier’s approved measuring and refill procedure. Track changes to the schedule when comparing periods.'],['Calculate from verified measurements','If measured use were 60ml across 30 actual run hours, the observed rate would be 2ml per hour. At the same conditions, 200 run hours would suggest 400ml. This is an arithmetic example, not a HUME performance claim.'],['Estimate cost using the quote','Multiply estimated millilitres by the approved oil’s quoted cost per millilitre and add relevant delivery or service costs. Recheck the estimate when settings or hours change; no fixed monthly cost is established here.']
],[['How long does the 1,000ml reservoir last?','No verified interval is published for this model. It depends on actual consumption.'],['What is the HUME HVAC rate in ml per hour?','A verified rate has not been confirmed. Request model-specific data and operating assumptions.'],['Can I use the arithmetic example as a specification?','No. The numbers illustrate calculation only and do not describe HUME equipment performance.']]),
guide('control-fragrance-intensity-hvac-scenting','How to Control Fragrance Intensity in HVAC Scenting','Control HVAC fragrance intensity using the settings approved for the supplied model, coordinated with air-system operation and occupant feedback. HUME’s HVAC interface and adjustment features need confirmation before purchase.',[
['Verify the available controls','Ask whether the exact model supports output adjustment, timed operation or another control method. Request the manual and setup instructions. Features advertised for other HVAC diffusers do not establish HUME capabilities.'],['Start with a restrained approved setting','Use the supplier’s recommended starting procedure and assess the intended zone. Gather feedback from staff present for long periods as well as visitors. A strong impression beside the machine is not the same as a balanced occupied-space experience.'],['Change one operating factor at a time','Document the approved setting, schedule and observed feedback. Review the air-system schedule before changing equipment operation. Do not compensate for closed ducts, excluded zones or unsuitable airflow simply by increasing fragrance.'],['Maintain a feedback process','Assign an operator who can pause or adjust operation according to instructions. Record complaints, changes and refill use. Review the plan when occupancy or ventilation changes instead of preserving settings indefinitely.']
],[['Does HUME HVAC have mobile app intensity control?','That feature has not been confirmed for the supplied HVAC model. Request documentation.'],['Should I increase output if a distant room has no scent?','Review distribution and zoning first rather than assuming higher output solves the problem.'],['How should intensity be evaluated?','Use feedback across the intended occupied zone and at different operating times.']]),
guide('when-business-choose-hvac-scenting','When Should a Business Choose HVAC Scenting?','Consider HVAC scenting when a compatible duct system serves the intended commercial zones and the business can coordinate installation, operation and refills. Choose a local standalone plan when duct integration or zone separation is unsuitable.',[
['Check the building’s suitability','Review air handlers, served zones and operating schedules. Confirm the building permits the proposed connection. Large floor area alone is not a reason to choose HVAC equipment.'],['Assess the operational commitment','Identify who manages installation approval, controls, inventory and maintenance access. Request approved oil and model documentation. A duct-connected purchase still requires an operating process.'],['Compare a standalone alternative','A reception or isolated local zone may be better assessed with standalone equipment. Compare reviewed placement and running costs rather than assuming HVAC is more effective for every business.'],['Make the decision from a complete brief','Use floor plans, height, ventilation, intended zones and excluded areas to request options. Evaluate the equipment price alongside installation scope and consumables. HUME’s ₹12,000 HVAC format is an enquiry option subject to review.']
],[['Is HVAC scenting only for large buildings?','Suitability follows the air system and zones, not a universal building-size threshold.'],['When should I avoid an HVAC proposal?','When compatibility, approvals, zone boundaries or occupant preferences do not support it.'],['What should I send HUME to compare options?','Your city, floor plan, HVAC layout, zone sizes, ceiling height, opening hours and excluded areas.']])
];
