type Section=[string,string];
const compact='hume-commercial-scent-machine-pro';
const large='800ml-commercial-diffuser';
const hvac='hume-hvac-scenting-system';
const tower='hume-pro-commercial-tower';
function guide(slug:string,title:string,description:string,product:string,sections:Section[],questions:Section[]){return {slug,title,description,product,sections,questions};}
export const machineGuides=[
guide('which-aroma-diffuser-business','Which Aroma Diffuser Do I Need for My Business?','Choose an aroma diffuser by the zone you want to scent, its ventilation and the installation format. Floor area helps shortlist equipment; it does not establish guaranteed coverage.',compact,[
['Start with the occupied zone','Measure reception, shop floor or lounge separately from rooms behind closed doors. Record ceiling height, entrances and operating hours. Tell the supplier whether people stay for a few minutes or a full workday.'],['Match the format to the building','Consider a standalone format for a local zone, a tower where equipment will sit in the interior, and HVAC equipment only after duct compatibility review. Passive reeds suit small corners rather than a commercial floor.'],['Compare HUME options','The 400ml Commercial Diffuser lists 1,000–2,000 sq ft at ₹4,190. The 800ml model lists up to 2,000 sq ft at ₹7,950. The Tower lists up to 1,500 sq ft at ₹9,650. Reservoir size and coverage are separate specifications.'],['Complete the selection','Send a floor plan and ask for a proposed position, approved fragrance and operating schedule. Confirm power, installation instructions, oil consumption assumptions and quote inclusions before ordering.']
],[['Which diffuser is best for every business?','No single model is best for every layout. Use the property brief to compare formats and zones.'],['Should I choose by bottle size?','No. Reservoir volume does not determine output, reach or room-to-room distribution.'],['What information should I send?','Your city, zone area, ceiling height, ventilation, room divisions and opening hours.']]),
guide('best-commercial-scent-machine-500-sq-ft','Best Commercial Scent Machine for 500 Sq Ft','For a 500 sq ft business, ask for a controllable local-zone diffuser and verify its minimum output. HUME’s listed commercial models have larger coverage figures, so do not assume they are automatically suitable for a small room.',compact,[
['Measure the actual 500 sq ft','A 20 ft by 25 ft rectangular floor is 500 sq ft. Confirm whether that is one open area or several rooms. Separate storage and food areas from the proposed scenting zone.'],['Avoid choosing excess output','A machine advertised for a larger floor may need a restrained setting in a small shop or cabin. Ask whether the exact model supports a suitable low output and request usage instructions. Higher listed coverage is not automatically a benefit.'],['Review a HUME model before purchase','The 400ml model is an equipment option to enquire about, not a confirmed 500 sq ft recommendation. Its listed range is 1,000–2,000 sq ft. Ask the team to assess your layout and control requirements first.'],['Test the occupied experience','Evaluate intensity at the entrance and where staff remain all day. Watch for shared air entering adjoining rooms. Agree on a way to adjust or pause operation rather than relying only on how the fragrance smells near the machine.']
],[['Is the 400ml model guaranteed for 500 sq ft?','No. Ask whether its adjustable output is suitable for your smaller zone.'],['Will a reed diffuser cover 500 sq ft?','The Mini Reed Diffuser lists up to 120 sq ft and should not be treated as a whole-shop system.'],['Does a smaller shop need less oil?','Consumption depends on output and operating hours; request a usage estimate.']]),
guide('best-commercial-scent-machine-1000-sq-ft','Best Commercial Scent Machine for 1,000 Sq Ft','For an open 1,000 sq ft commercial zone, the 400ml Commercial Diffuser is a HUME option to assess: it lists 1,000–2,000 sq ft at ₹4,190. Confirm ventilation, ceiling height and room divisions before selecting it.',compact,[
['Check the open-area assumption','A 25 ft by 40 ft floor is 1,000 sq ft. If partitions create separate rooms, do not assume one machine reaches them evenly. Mark air-conditioning outlets and frequently opened doors on the plan.'],['Compare relevant equipment','The 400ml model’s listed range includes 1,000 sq ft. The Tower and 800ml models are other formats to compare when position, reservoir capacity or interior appearance matter. More capacity does not prove better coverage.'],['Plan the operating schedule','Share daily opening hours and whether ventilation stays on throughout. Ask for an approved intensity and refill estimate based on those conditions. Up to a month between refills is usage-dependent, not a fixed schedule.'],['Review placement with the supplier','Use the supplied model instructions to agree a stable, accessible position. Keep refill access and customer movement in mind. Confirm mounting and electrical requirements separately.']
],[['Can one machine scent 1,000 sq ft?','It may be considered for an appropriate open zone, but the floor plan and airflow need review.'],['What is the 400ml price?','The listed equipment price is ₹4,190; confirm GST, delivery and fragrance inclusions.'],['What if my 1,000 sq ft has four rooms?','Assess the rooms independently instead of assuming one unit serves all four.']]),
guide('best-commercial-scent-machine-2000-sq-ft','Best Commercial Scent Machine for 2,000 Sq Ft','For a 2,000 sq ft open commercial zone, compare HUME’s 400ml and 800ml diffusers. Both list coverage reaching 2,000 sq ft; the 800ml reservoir is larger, not proof of greater reach.',large,[
['Review the upper coverage limit','A 40 ft by 50 ft rectangle is 2,000 sq ft. This sits at the listed upper figure for these models, so account for high ceilings, fresh-air extraction and open entrances before choosing a single unit.'],['Compare price and reservoir','The 400ml model is ₹4,190 and the 800ml model is ₹7,950. Compare refill access and expected consumption alongside hardware cost. Do not infer a doubled refill interval from a doubled reservoir.'],['Identify distribution obstacles','Mark partitions, corridors and isolated corners. Ask whether one position is appropriate or whether the property should be divided into local zones. Two units are not automatically required simply because the space reaches the upper figure.'],['Confirm through a zone proposal','Request equipment locations, settings and consumption assumptions for your actual floor plan. Review staff and visitor feedback before increasing intensity or extending the plan to other rooms.']
],[['Which HUME model lists 2,000 sq ft?','The 400ml lists 1,000–2,000 sq ft; the 800ml lists up to 2,000 sq ft. These are indicative figures.'],['Is 800ml more powerful than 400ml?','Reservoir volume alone does not establish comparative output or power.'],['Is one unit enough at the maximum figure?','Only a review of the zone can answer; the listed figure is not a guarantee.']]),
guide('best-commercial-scent-machine-5000-sq-ft','Best Commercial Scent Machine for 5,000 Sq Ft','HUME’s HVAC Scenting System lists up to 5,000 sq ft at ₹12,000. It is a duct-connected option requiring technical review; a 5,000 sq ft site without compatible ducts needs a separate zone plan.',hvac,[
['Distinguish floor area from ducts','A 50 ft by 100 ft floor is 5,000 sq ft, but that does not describe air distribution. Share air-handler zoning, duct drawings and operating hours before discussing HVAC equipment.'],['Assess the listed HVAC option','The HUME HVAC format lists a 1,000ml reservoir and up to 5,000 sq ft. Confirm the supplied model’s controls, oil pairing and connection requirements. Installation is not automatically included in the equipment price.'],['Plan non-HVAC zones separately','If the building uses split AC or has isolated rooms, consider standalone units by zone. Do not divide 5,000 by a catalog coverage number and treat the result as an installation plan.'],['Agree technical responsibilities','Identify who approves the duct connection, installs the equipment and verifies the result. Keep unscented areas and shared return air in the review. Confirm refill access and ongoing operating responsibilities.']
],[['Does the HVAC model guarantee 5,000 sq ft?','No. The listed figure is indicative; compatibility and distribution must be reviewed.'],['Can I use it without central ducts?','Do not assume a duct-connected model suits a non-ducted site.'],['Is ₹12,000 the complete project cost?','It is the listed equipment price. Confirm taxes, delivery, installation and consumables separately.']]),
guide('best-commercial-scent-machine-10000-sq-ft','Best Commercial Scent Machine for 10,000 Sq Ft','A 10,000 sq ft property needs a zoning and airflow assessment. HUME does not list a single machine verified for 10,000 sq ft; compare a reviewed HVAC proposal with a multi-zone standalone plan.',hvac,[
['Map a large property into zones','Separate reception, circulation, tenant areas and closed rooms. Record ceiling heights and air handlers for each zone. Total building area is not the same as the area that should be scented.'],['Do not double a coverage claim','The HUME HVAC format lists up to 5,000 sq ft. Two units do not automatically guarantee 10,000 sq ft, because ducts, output and zone boundaries can overlap or leave areas unserved.'],['Compare deployment options','A compatible duct system may support a technically reviewed HVAC proposal. Other sites may need several independent local-zone machines. Ask the supplier to justify positions and count using the layout rather than a simple area ratio.'],['Prepare a staged rollout','Begin with an agreed zone, record feedback and review consumption before expanding. Request an itemised project quote covering equipment, installation responsibilities, oil and support for each phase.']
],[['Does HUME have a 10,000 sq ft machine?','No single model with verified 10,000 sq ft coverage is listed in the current catalog.'],['Will two HVAC units be enough?','Not automatically. Equipment count must follow the air-handler and zoning review.'],['How should I request a large-site quote?','Send the floor plan, duct layout, zone areas, opening hours and areas to leave unscented.']]),
guide('calculate-aroma-diffuser-coverage-square-feet','How to Calculate Aroma Diffuser Coverage by Square Feet','Calculate rectangular floor area as length × width in feet. Use the result to describe a zone, then assess ceiling height, ventilation and partitions; floor area alone cannot calculate a diffuser’s effective coverage.',compact,[
['Measure a rectangular floor','For a 20 ft by 25 ft room, area is 20 × 25 = 500 sq ft. Measure the usable zone rather than including adjacent spaces behind closed doors. If measurements are in metres, square metres × 10.764 gives approximate square feet.'],['Add irregular sections','Break an L-shaped floor into non-overlapping rectangles, calculate each area and add them. For example, 20 × 20 plus 10 × 15 gives 550 sq ft. Avoid double-counting the intersection.'],['Record height and airflow','Two rooms with the same floor area can have different air volumes. Record ceiling height separately; length × width × height gives cubic feet for a rectangular room. This describes volume but is not a validated diffuser-sizing formula.'],['Use catalog coverage as a shortlist','Compare the zone area with listed coverage, then submit a layout for review. No universal airflow multiplier or square-foot formula establishes the machine count for every property.']
],[['What is the square-foot formula?','For a rectangle, multiply length in feet by width in feet.'],['Can I calculate scent coverage from floor area alone?','No. Ventilation, height, zoning and equipment output also affect suitability.'],['How do I convert square metres?','Multiply square metres by approximately 10.764 to obtain square feet.']]),
guide('how-many-scent-machines-space','How Many Scent Machines Do I Need for My Space?','Count scent machines by independently reviewed zones, not by dividing total area by advertised coverage. Separate rooms and air systems can require different placements even in a small property.',large,[
['Identify independent zones','List areas divided by walls, closed doors or different ventilation systems. Mark which should receive fragrance and which should remain unscented. That zone map is the starting point for a machine-count proposal.'],['Consider one open area differently','A suitable open reception may be considered for one machine within its indicative range. A property with several enclosed rooms needs separate distribution decisions even if its combined area is the same.'],['Use arithmetic only as an illustration','For example, dividing 4,000 sq ft by a listed 2,000 sq ft figure gives two, but that is not a verified recommendation. The result ignores partitions, ceiling height, open doors, machine placement and airflow.'],['Request a justified equipment schedule','Ask for a table showing each zone, proposed model, position and operating hours. Include approved oil and consumption assumptions. Review overlap and excluded areas before ordering multiple units.']
],[['Is area divided by coverage a reliable machine count?','No. It is only a rough arithmetic illustration and cannot replace zoning review.'],['Does each room need a machine?','Not necessarily, but each room needs a placement and airflow decision.'],['Can more machines create too much fragrance?','Overlapping zones can lead to excessive intensity; coordinate settings and gather feedback.']]),
guide('what-size-scent-machine-business','What Size Scent Machine Does My Business Need?','Choose machine size using the zone’s layout and operating conditions. Compare reservoir capacity, output controls and indicative coverage separately rather than treating millilitres as a coverage rating.',compact,[
['Separate the three specifications','Reservoir size describes oil volume. Coverage is an indicative area claim. Controls describe how the model operates. None of these alone determines whether equipment suits your business.'],['Match the zone first','Measure the intended area, room divisions and ceiling height. Explain entrance traffic and ventilation. Identify whether you need a local standalone format or a reviewed duct connection.'],['Review capacity for refill access','A larger reservoir may change how much oil can be held, but usage still depends on settings and opening hours. Ask for a consumption estimate rather than assuming a fixed monthly refill interval.'],['Compare the full purchase','Include hardware, approved refills, installation requirements and support. Ask for the model manual and actual specifications before choosing a larger unit solely because it seems more future-proof.']
],[['Is 800ml always better than 400ml?','No. Both HUME models list coverage reaching 2,000 sq ft; the larger reservoir is a different specification.'],['What matters besides square feet?','Ceiling height, partitions, ventilation, doors, operating hours and placement.'],['Can I buy a larger unit for expansion?','Confirm whether it can operate appropriately in the current zone; future area alone is not sufficient justification.']]),
guide('best-scent-machine-small-shop','Best Scent Machine for a Small Shop','For a small shop, prioritise adjustable intensity, sensible placement and affordable approved refills. Confirm that a commercial model can operate appropriately in your shop’s smaller zone before buying.',compact,[
['Define the customer area','Measure the trading floor separately from stockrooms and closed offices. Note frequently opened doors and whether air moves into neighbouring units. A small-shop label is less useful than actual dimensions.'],['Check low-output suitability','Ask the supplier whether the model supports restrained operation in your measured zone. The HUME 400ml range begins at a listed 1,000 sq ft, so a much smaller shop needs a specific suitability discussion.'],['Avoid conflicts with merchandise','Consider food, cosmetics and fragrance products sold in the shop. The ambient fragrance should not compete with products customers are evaluating. Keep preparation and storage areas outside a general scent plan.'],['Keep operation simple','Agree a schedule, approved refill and staff responsibility. Compare oil cost and delivery charges with equipment price. Evaluate feedback before changing settings or extending operation into other rooms.']
],[['Is the personal diffuser a whole-shop machine?','The Car & Room Diffuser is for personal spaces and has no confirmed square-foot rating; do not assume whole-shop coverage.'],['Can I use reeds instead?','The Mini Reed Diffuser is a passive small-area option, listed up to 120 sq ft, not a general shop-floor system.'],['How do I enquire for a small shop?','Share measured area, layout, merchandise type, ventilation and opening hours.']]),
guide('best-scent-machine-large-commercial-spaces','Best Scent Machine for Large Commercial Spaces','Large commercial spaces need a planned distribution system. Compare HVAC equipment only for compatible ducts and standalone machines for defined local zones; building area alone does not identify a best model.',hvac,[
['Map height as well as area','Atriums and high-ceiling showrooms can differ substantially from standard-height offices with the same floor area. Include ceiling profiles, air systems and entrance conditions in the brief.'],['Choose distribution architecture','Discuss ducted distribution with technical reviewers when appropriate. For separate or non-ducted zones, compare local standalone positions. One high-capacity reservoir is not evidence of whole-building reach.'],['Coordinate building operations','Identify management permissions, installation access, power and refill routes. Keep tenant areas, food zones and unscented areas in the plan. Agree who can change settings and who responds to feedback.'],['Budget for deployment and operation','Request a zone-by-zone equipment list and recurring consumables estimate. Clarify installation scope and support availability. Use a staged assessment before treating a large catalog coverage figure as a project commitment.']
],[['Is HVAC always best for a large space?','No. It depends on duct compatibility, air-handler zoning and which areas should be scented.'],['Can standalone machines serve a large site?','They can be considered by local zone; count and placement need assessment.'],['What is HUME’s largest listed coverage?','The HVAC format lists up to 5,000 sq ft, subject to technical compatibility and airflow review.']]),
guide('best-scent-diffuser-reception-area','Best Scent Diffuser for a Reception Area','Choose a reception diffuser by area, entrance airflow and how long staff remain in the space. A tower or standalone commercial format can be considered for suitable zones; a desk-sized corner is a separate use case.',tower,[
['Measure where visitors wait','Map entrance, seating and reception desk, including air movement from adjacent corridors. Frequent doors can change the experience. Distinguish a small desk corner from the entire reception floor.'],['Compare interior and operating fit','The HUME Tower offers an interior-facing format at ₹9,650 with a listed 500ml capacity and up to 1,500 sq ft. Compare the 400ml and 800ml models where their format and indicative range fit the plan.'],['Prioritise reception staff feedback','Staff may experience fragrance for a full shift while visitors stay briefly. Start with restrained operation and establish a process for adjustments. Do not choose intensity solely from a short entrance impression.'],['Keep access practical','Review power, customer circulation and refill access with supplied instructions. Confirm the model’s placement requirements. Avoid blocking pathways or assuming that placing equipment behind a desk guarantees distribution.']
],[['Which HUME product can I assess for reception?','Compare the Tower, 400ml and 800ml commercial models against the actual reception zone.'],['Can reeds scent a whole reception?','The Mini Reed Diffuser is for a small local area, not a whole reception assumption.'],['Does reception need a signature fragrance?','An approved catalog fragrance can be considered; bespoke exclusivity is a separate service to confirm.']]),
guide('best-wall-mounted-commercial-aroma-diffusers','Best Wall-Mounted Commercial Aroma Diffusers','Choose a wall-mounted diffuser only after verifying the exact model’s mounting approval, brackets, power requirements and refill access. HUME’s current catalog does not confirm a wall-mount specification for its commercial models.',compact,[
['Verify the mounting specification','Ask for the supplied manual, approved orientation, bracket details and required clearances. A compact appearance or online photo does not prove that a model can be wall mounted.'],['Review the wall and access','Confirm who assesses the mounting surface, power connection and access for refills. Obtain property approval where needed. Follow manufacturer instructions rather than improvising a bracket or orientation.'],['Assess airflow after mounting','A higher position does not automatically improve scent distribution. Review nearby outlets, extraction and occupied areas with the supplier. Keep practical maintenance access in the placement decision.'],['Enquire without assuming availability','The featured HUME 400ml product is a model to discuss, not a verified wall-mounted recommendation. Request explicit confirmation for the supplied unit before purchase. If unavailable, compare an approved standalone placement.']
],[['Are HUME commercial models confirmed wall-mountable?','No wall-mount approval is confirmed in the current catalog. Ask for exact model documentation.'],['Can I mount a standalone model myself?','Do not assume that it supports a different orientation or bracket; follow approved instructions.'],['Is wall installation included in the price?','Mounting availability, responsibility, materials and charges require confirmation.']]),
guide('best-standalone-commercial-aroma-diffusers','Best Standalone Commercial Aroma Diffusers','Compare standalone commercial diffusers by zone fit, controls, reservoir size, placement and approved oil cost. HUME’s 400ml, 800ml and Tower formats provide different starting points for local-zone enquiries.',large,[
['Compare the catalog options','The 400ml is ₹4,190 with listed 1,000–2,000 sq ft coverage. The 800ml is ₹7,950 with up to 2,000 sq ft. The Tower is ₹9,650 with a 500ml reservoir and up to 1,500 sq ft. Confirm actual specifications and inclusions.'],['Choose controls you will use','The 400ml and 800ml models list Wi-Fi, Bluetooth and mobile app control. The Tower lists Bluetooth app control and multiple schedules. Verify phone compatibility and setup requirements for the supplied model.'],['Plan one local zone at a time','A standalone format does not imply even distribution between separate rooms. Review position, partitions, doors and ventilation. Keep refill access and the interior’s circulation requirements in mind.'],['Compare ongoing operation','Request approved oil prices and a usage estimate for your opening hours. Up to a month between refills on the 400ml and 800ml models is usage-dependent. Confirm stock, warranty and delivery before ordering.']
],[['Which standalone diffuser has the biggest listed reservoir?','Among these HUME standalone commercial options, the 800ml model has the largest listed reservoir.'],['Does standalone mean no setup?','No. Placement, power, app configuration and approved refill instructions still need confirmation.'],['Is the tower’s higher price proof of greater coverage?','No. The Tower lists up to 1,500 sq ft; price and coverage are separate comparisons.']]),
guide('commercial-scent-machine-buying-guide-indian-businesses','Commercial Scent Machine Buying Guide for Indian Businesses','Indian businesses should compare commercial scent machines using a measured property brief, approved oil pairing and itemised equipment and running costs. Confirm local delivery, installation responsibilities and written support terms.',compact,[
['Prepare the property brief','Provide city, property type, zone area, ceiling height, ventilation and operating hours. Include a floor plan and spaces to leave unscented. Give the same brief to each supplier for comparable proposals.'],['Shortlist the equipment format','Consider standalone machines for reviewed local zones and HVAC equipment for technically compatible ducts. Compare controls, reservoir size and indicative coverage separately. Do not assume one machine serves multiple enclosed rooms.'],['Request an itemised Indian quote','Separate equipment, GST, freight, approved oils and installation charges. Confirm stock and delivery to your city. Ask whether the quoted price includes fragrance and whether consumable reorders incur additional shipping.'],['Check the purchase and support terms','Obtain warranty duration, exclusions, return conditions and fault-reporting steps in writing. Review the supplied manual and refill instructions. Decide who operates the equipment and manages oil inventory before rollout.']
],[['Do HUME prices include GST and freight?','Confirm taxes, delivery and included fragrance in the written quote; do not assume they are included in listed equipment prices.'],['Is a monthly running cost published?','No verified fixed monthly cost is published. Ask for oil prices and consumption assumptions for your schedule.'],['Can HUME deliver and install in my city?','Enquire with your city and property brief; delivery and installation availability require confirmation.']])
];
