import {products} from './content';
type Product=typeof products[number];
export function productUseCases(p:Product){if(p.slug==='hume-mini-reed-diffuser-50ml')return [{name:'Hotel desks',path:'/industries/hotels'},{name:'Office desks',path:'/industries/offices'},{name:'Spa reception corners',path:'/industries/spas'},{name:'Salon waiting corners',path:'/industries/salons'}];if(p.slug==='hume-hvac-scenting-system')return [{name:'Hotels',path:'/industries/hotels'},{name:'Offices',path:'/industries/offices'},{name:'Malls',path:'/industries/malls'},{name:'Showrooms',path:'/industries/showrooms'}];if(p.slug==='hume-pro-commercial-tower')return [{name:'Hotel lobbies',path:'/industries/hotels'},{name:'Retail stores',path:'/industries/retail'},{name:'Showrooms',path:'/industries/showrooms'},{name:'Spa receptions',path:'/industries/spas'},{name:'Resort lounges',path:'/industries/resorts'},{name:'Office receptions',path:'/industries/offices'}];return [{name:'Hotels',path:'/industries/hotels'},{name:'Gyms',path:'/industries/gyms'},{name:'Offices',path:'/industries/offices'},{name:'Retail stores',path:'/industries/retail'},{name:'Showrooms',path:'/industries/showrooms'},{name:'Salon receptions',path:'/industries/salons'}];}
export function productFaqs(p:Product){const reed=p.slug==='hume-mini-reed-diffuser-50ml';const hvac=p.slug==='hume-hvac-scenting-system';const tower=p.slug==='hume-pro-commercial-tower';const uses=productUseCases(p).map(i=>i.name).join(', ');return [
{q:`Where can the ${p.name} be used?`,a:`The ${p.name} can be considered for ${uses.toLowerCase()}. ${reed?'It is a small-area reed format, not a whole-property scenting system.':hvac?'Each proposed area needs a duct-system compatibility and zoning review.':'Review each area’s layout, ventilation and user preferences before choosing equipment.'}`},
{q:`What is the fragrance capacity of the ${p.name}?`,a:`The listed fragrance capacity is ${p.capacity}. ${reed?'Confirm the supplied reed fragrance and replacement instructions.':'Oil capacity describes the reservoir size; it does not establish a guaranteed refill interval.'}`},
{q:`How much area does the ${p.name} cover?`,a:`Listed coverage: ${p.coverage}. This is indicative, not guaranteed. Ceiling height, ventilation, open doors, room divisions and operating conditions affect suitability. ${reed?'Discuss a desk or small corner rather than assuming coverage of a hotel lobby.':hvac?'A floor-area figure does not establish HVAC or multi-zone compatibility.':'Review the actual zone before relying on the listed floor-area figure.'}`},
{q:`What is the price of the ${p.name}?`,a:`The listed equipment price is ₹${p.price.toLocaleString('en-IN')}. Confirm GST, delivery charges, availability and any included fragrance before ordering. A WhatsApp enquiry does not place an order.`},
{q:`Does the ${p.name} have app or wireless control?`,a:reed?'This reed diffuser uses passive diffusion and does not require a plug or mobile app.':hvac?'The listed format is duct-connected. App controls and operating interfaces must be confirmed for the actual HVAC model before ordering.':tower?'The Tower Commercial Diffuser lists Bluetooth app control and multiple schedules. Confirm app compatibility and setup requirements for the supplied model.':`${p.name} has Wi-Fi and Bluetooth connectivity with mobile app control. Confirm phone compatibility and setup instructions before purchase.`},
{q:`Which fragrance should I use with the ${p.name}?`,a:reed?'Use the reed fragrance approved for the Mini Reed Diffuser. Reed liquid is not a machine refill. Confirm the supplied fragrance and replacement guidance.':`Use fragrance oil approved for the ${p.name}. Do not assume perfume, essential oil or reed liquid can be used as a machine refill. Confirm the formula and refill instructions before use.`},
{q:`How often does the ${p.name} need refilling?`,a:reed?'Refill or replacement timing has not been verified. Follow the supplied instructions and confirm the replacement options for this 50 ml reed format.':hvac||tower?'No verified refill interval is available for this model. Usage depends on output, operating hours, oil formula and airflow. Ask for a usage estimate based on your schedule.':`The ${p.name} is described as offering up to a month between refills. This is usage-dependent, not a guarantee. Higher output or longer operating hours can require earlier refilling.`},
{q:`How is the ${p.name} installed or placed?`,a:p.installation+' Installation availability and any charges must be confirmed separately.'},
{q:`Can one ${p.name} serve separate rooms?`,a:reed?'This compact reed format should be considered for a local desk or corner. Separate rooms require separate placement decisions.':hvac?'Potential distribution through ducts must be reviewed against the air-handler layout and zoning. A shared HVAC system does not guarantee even fragrance distribution.':'Do not assume one machine serves separate rooms evenly. Share a floor plan and ventilation details to assess each zone.'},
{q:`What are the ongoing costs of the ${p.name}?`,a:reed?'Ask about replacement fragrance and reeds, pack sizes and prices. A verified replacement interval is needed before estimating monthly costs.':'Request approved oil prices, bottle sizes and consumption assumptions separately from equipment pricing. No fixed monthly cost is verified for this model.'},
{q:`Does the ${p.name} include delivery, warranty or support?`,a:'Delivery timing and charges, warranty duration, exclusions, returns and support arrangements must be confirmed in writing before ordering. This website does not promise an installation service or a specific warranty.'},
{q:`How do I enquire about the ${p.name}?`,a:`Use the product’s WhatsApp enquiry button to contact HUME Spaces on +91 9559024822. Include your city, property type, area, ventilation and operating hours. Ask for an itemised quote and an approved oil pairing.`}
];}
