type Pair=[string,string];
// Commercial enquiries use confirmed catalog specifications, not assumed service packages.
const briefs:[string,string][]=[
 ['Pilates Studio Scenting Solutions India','Compare optional reception equipment with a separate reformer-room decision; send the studio layout and class timetable.'],
 ['Yoga Studio Scenting Solutions India','Start with permitted arrival zones and participant preferences; yoga practice rooms may remain fragrance-free.'],
 ['Barre Studio Scenting Solutions India','Plan reception separately from fixed barre stations, class positions and instructor routes.'],
 ['Boutique Fitness Scenting Solutions India','Request a zone-specific proposal for the actual disciplines, airflow and occupied hours instead of one setting for the whole venue.'],
 ['Pilates Studio Fragrance Solutions India','Prepare desired reception notes, notes to avoid and reformer-room exclusions before requesting a formula and equipment pairing.'],
 ['Yoga Studio Fragrance Solutions India','Review venue policy, existing aromas and an unscented option before requesting a complete fragrance composition.'],
 ['Boutique Fitness Fragrance Solutions India','Compare complete catalog concepts against the brand brief and confirm supply, liquid compatibility and permitted zones.'],
 ['Pilates Studio Aroma Diffuser India','Enquire about the 400ml Commercial Diffuser for a suitable permitted zone after area, height and reformer placement review.'],
 ['Yoga Studio Aroma Diffuser India','Assess a commercial machine for approved arrival areas without assuming that diffusion is wanted during yoga classes.'],
 ['Barre Studio Aroma Diffuser India','Compare a suitable machine with dry placement, clear class routes and confirmed servicing access.'],
 ['Commercial Aroma Diffuser for Pilates Studio','Match a commercial machine to an approved studio zone, supported controls and measured airflow rather than equipment label alone.'],
 ['Commercial Aroma Diffuser for Yoga Studio','Request a device and approved-liquid pairing for a permitted zone; a commercial label does not establish participant comfort.'],
 ['Commercial Fragrance Diffuser for Boutique Fitness Studio','Select by zone area, class schedule, placement and recurring oil responsibility; full-studio coverage is not assumed.'],
 ['Pilates Studio Scent Machine India','Compare the 400ml and 800ml models using the intended permitted zone and refill plan.'],
 ['Yoga Studio Scent Machine India','Request equipment for a permitted arrival zone with clear practice-room boundaries and stop procedures.'],
 ['Boutique Fitness Scent Machine India','The 800ml model offers a larger reservoir, not a promise of larger coverage or a fixed monthly refill interval.'],
 ['Pilates Studio Air Freshener Machine','A scent machine adds optional ambience; it does not replace cleaning, source-odour control or ventilation.'],
 ['Yoga Studio Fragrance Machine','Assess the exact model and approved liquid with participant preferences, room policy and connected air paths documented.'],
 ['Premium Pilates Studio Scenting Solution','A premium brief can coordinate service, interiors and optional reception fragrance; stronger output does not prove luxury.'],
 ['Luxury Pilates Studio Fragrance Solution','Choose a complete composition against the studio identity and member feedback rather than assume a luxury-named note suits everyone.'],
 ['Premium Yoga Studio Fragrance Solution','Plan an understated arrival identity only where permitted, retaining fragrance-free practice when appropriate.'],
 ['Boutique Fitness Studio Signature Scent Service','Enquire about formula supply and any development scope; exclusivity, samples and managed visits require written confirmation.'],
 ['Custom Signature Scent for Pilates Studio','Submit a Pilates brand brief, preferred directions, exclusions and quantities, then confirm development availability, rights and costs.'],
 ['Custom Signature Scent for Yoga Studio','Define permitted zones and participant preferences before asking whether a custom formula can be developed and supplied.'],
 ['Custom Signature Scent for Barre Studio','Prepare the barre brand identity, notes to avoid, trial criteria and ownership requirements before a custom-development enquiry.'],
 ['Pilates Studio Scent Marketing Company India','Evaluate HUME Spaces equipment and fragrance enquiries using confirmed specifications, quote inclusions and branch requirements.'],
 ['Yoga Studio Scent Marketing Company India','Compare supplier scope against reception-only or permitted-zone needs, fragrance-free policies and installation availability.'],
 ['Boutique Fitness Scent Marketing Company India','Ask a supplier to distinguish equipment, approved oils and any service work rather than assume a complete managed package.'],
 ['Pilates Studio Scent Branding Company','Request a documented formula and usage brief across permitted Pilates zones; recognition or member retention is not guaranteed.'],
 ['Yoga Studio Scent Branding Company','Define a voluntary arrival identity with practice-room exclusions; no meditation, breathing or wellbeing result is promised.'],
 ['Fitness Studio Fragrance Supplier India','Ask about available compositions, exact machine approval, recurring quantities and delivery to your postcode.'],
 ['Pilates Studio Fragrance Oil Supplier India','Confirm approved liquid for the exact machine, stock, quantity and formulation; reservoir capacity alone does not predict consumption.'],
 ['Yoga Studio Aroma Oil Supplier India','Confirm machine-liquid approval and venue permission; ambient machine oil is not assumed suitable for skin, massage or ingestion.'],
 ['Boutique Fitness Diffuser Machine Supplier India','Compare catalog machines with written delivery, installation, warranty and support scope for your location.'],
 ['Waterless Diffuser for Pilates Studio','Waterless equipment uses an approved liquid without user-added water; exact liquid and refill instructions must be confirmed.'],
 ['Waterless Diffuser for Yoga Studio','Consider waterless equipment only for permitted zones and an approved formulation; the technology does not establish universal suitability.'],
 ['Cold-Air Diffuser for Boutique Fitness Studio','Compare cold-air equipment with the approved zone and liquid brief; no air-purification or exercise-performance benefit is claimed.'],
 ['Smart Aroma Diffuser for Pilates Studio','The 400ml and 800ml models list Wi-Fi, Bluetooth and app control; confirm exact app, setup and supported scheduling before purchase.'],
 ['Automatic Fragrance Machine for Yoga Studio','Confirm supported schedules and who can stop diffusion; automatic operation does not remove the need for policy and member-feedback review.'],
 ['Wall-Mounted Aroma Diffuser for Pilates Studio','Mounting suitability and supplied hardware are unconfirmed; ask about exact installation approval before selecting a wall location.'],
 ['Aroma Diffuser for 500 Sq Ft Pilates Studio','A 500 sq ft area is not a guaranteed match to a catalog setting; review occupied positions and permitted output before choosing equipment.'],
 ['Aroma Diffuser for 1,000 Sq Ft Pilates Studio','The 400ml model lists 1,000–2,000 sq ft reference coverage; confirm the actual layout, height and air paths for the permitted zone.'],
 ['Aroma Diffuser for 2,000 Sq Ft Pilates Studio','Compare the 400ml and 800ml models at their listed reference range, with coverage subject to layout and operating review.'],
 ['Aroma Diffuser for 3,000 Sq Ft Boutique Fitness Studio','A 3,000 sq ft venue exceeds the listed coverage of one 400ml or 800ml model; request a zoned assessment rather than a single-machine guarantee.'],
 ['Fragrance Solution for Pilates Reception','Assess reception area, door opening and waiting seats, with discharge kept away from occupants and reformer-room migration reviewed.'],
 ['Fragrance Solution for Pilates Reformer Room','Confirm whether the reformer room should remain unscented before proposing equipment; avoid direct discharge and apparatus obstruction.'],
 ['Fragrance Solution for Yoga Practice Room','A fragrance-free yoga practice room is a valid choice; any optional pairing requires venue permission and participant-feedback review.'],
 ['Fragrance Solution for Barre Studio','Separate arrival ambience from the class room and assess fixed barre positions, circulation and member preference.'],
 ['Complete Fragrance Solution for Boutique Fitness Studio','Request an itemised proposal for permitted zones, machines, approved oils and confirmed service scope, with class areas decided separately.'],
 ['Best Commercial Scenting System for Pilates & Yoga Studios','Best means fit for the approved studio brief, not an independently tested universal winner; compare room policy, equipment and ongoing costs.'],
];
export const studioCommercialPages=briefs.map(([title,brief],index)=>({
 slug:title.toLowerCase().replace(/['?]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),
 title,
 product:[3,6,15,21,27,30,33,42,43,48,49].includes(index)?'800ml-commercial-diffuser':'hume-commercial-scent-machine-pro',
 description:brief,
 sections:[
  ['What to enquire about',brief],
  ['Prepare this studio quotation brief','For '+title+', send the city and postcode, studio discipline, permitted-zone area, ceiling height, class schedule, occupancy, doors and air paths. Include member preferences, existing product aromas and areas to keep unscented. '+brief],
  ['Compare machines, approved oils and total costs','The 400ml Commercial Diffuser is listed at ₹4,190 with a 400 ml reservoir and 1,000–2,000 sq ft reference coverage. The 800ml Commercial Diffuser is ₹7,950 with an 800 ml reservoir and up to 2,000 sq ft reference coverage. A larger reservoir does not establish greater coverage or a fixed refill duration. Confirm stock, GST, delivery, approved oil, installation, warranty and support in writing.'],
  ['Agree the permitted rollout','Decide reception and practice rooms separately. Respect venue policy, member preferences and fragrance-free choices; review migration through shared air paths. Scent does not replace cleaning or ventilation, and no therapeutic or exercise-performance benefit is claimed. Custom development, sample supply and managed service availability require confirmation. '+brief],
 ] as Pair[],
 questions:[
  ['Which option should I enquire about?',brief],
  ['What is included in the listed price?','The catalog figure is an equipment reference. Confirm GST, delivery, approved oil, installation, warranty and support; these are not automatically included.'],
  ['Can HUME Spaces supply my city or postcode?','Send your city and postcode to confirm delivery timing and service scope. A nearby branch or onsite visit is not assumed.'],
  ['Should every class room be scented?','No. Reception and practice rooms need separate decisions. Venue policy and participant preferences may require unscented operation and review of shared air paths.'],
  ['Does an 800ml machine cover more than a 400ml machine?','Not automatically. The 400ml model lists 1,000–2,000 sq ft and the 800ml model up to 2,000 sq ft reference coverage. Larger tank capacity alone does not prove greater coverage or a monthly refill interval.'],
  ['How do I request a complete quote?','Send the studio layout, permitted-zone dimensions, height, occupancy, class hours and exclusions on WhatsApp. Ask for the exact model, approved oil and all quote inclusions in writing.'],
 ] as Pair[],
}));
export const studioCommercialClusters=[
 {title:'Studio and discipline solutions',start:0,end:7},
 {title:'Machines and premium briefs',start:7,end:21},
 {title:'Signature identity and supplier enquiries',start:21,end:34},
 {title:'Technology, controls and area selection',start:34,end:44},
 {title:'Reception, practice rooms and complete proposals',start:44,end:50},
];
